// veda64 API Hooking for Windows ARM64 - Implementation
// Uses veda64 disassembler for instruction analysis and relocation
// Uses direct NT syscalls instead of Win32 API for stealth
// Auto-generated by parse_arm64_xml.py

#include "hook.hpp"

// Only compile on Windows
#if defined(_WIN32) || defined(VEDA64_HOOK_SUPPORT)

#include <Windows.h>
#include <winternl.h>
#include <vector>
#include <unordered_map>
#include <mutex>
#include <algorithm>
#include <cstring>
#include <cstdio>

// ============================================================================
// NT API Definitions
// ============================================================================

// NT status codes
#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS ((NTSTATUS)0x00000000L)
#endif

#ifndef STATUS_INFO_LENGTH_MISMATCH
#define STATUS_INFO_LENGTH_MISMATCH ((NTSTATUS)0xC0000004L)
#endif

// Pseudo handles
#define NtCurrentProcess() ((HANDLE)(LONG_PTR)-1)
#define NtCurrentThread() ((HANDLE)(LONG_PTR)-2)

// System information classes
typedef enum _SYSTEM_INFORMATION_CLASS_EX {
    SystemBasicInformationEx = 0,
    SystemProcessInformationEx = 5,
} SYSTEM_INFORMATION_CLASS_EX;

// Client ID structure (if not defined)
#ifndef _CLIENT_ID_DEFINED
#define _CLIENT_ID_DEFINED
typedef struct _CLIENT_ID {
    HANDLE UniqueProcess;
    HANDLE UniqueThread;
} CLIENT_ID, *PCLIENT_ID;
#endif

// Object attributes (if not defined)
#ifndef _OBJECT_ATTRIBUTES_DEFINED
#define _OBJECT_ATTRIBUTES_DEFINED
typedef struct _OBJECT_ATTRIBUTES {
    ULONG Length;
    HANDLE RootDirectory;
    PUNICODE_STRING ObjectName;
    ULONG Attributes;
    PVOID SecurityDescriptor;
    PVOID SecurityQualityOfService;
} OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;
#endif

#ifndef InitializeObjectAttributes
#define InitializeObjectAttributes(p, n, a, r, s) { \
    (p)->Length = sizeof(OBJECT_ATTRIBUTES); \
    (p)->RootDirectory = r; \
    (p)->Attributes = a; \
    (p)->ObjectName = n; \
    (p)->SecurityDescriptor = s; \
    (p)->SecurityQualityOfService = NULL; \
}
#endif

// System basic information
typedef struct _SYSTEM_BASIC_INFORMATION {
    ULONG Reserved;
    ULONG TimerResolution;
    ULONG PageSize;
    ULONG NumberOfPhysicalPages;
    ULONG LowestPhysicalPageNumber;
    ULONG HighestPhysicalPageNumber;
    ULONG AllocationGranularity;
    ULONG_PTR MinimumUserModeAddress;
    ULONG_PTR MaximumUserModeAddress;
    ULONG_PTR ActiveProcessorsAffinityMask;
    CCHAR NumberOfProcessors;
} SYSTEM_BASIC_INFORMATION, *PSYSTEM_BASIC_INFORMATION;

// System thread information (within process info)
typedef struct _SYSTEM_THREAD_INFORMATION_EX {
    LARGE_INTEGER KernelTime;
    LARGE_INTEGER UserTime;
    LARGE_INTEGER CreateTime;
    ULONG WaitTime;
    PVOID StartAddress;
    CLIENT_ID ClientId;
    LONG Priority;
    LONG BasePriority;
    ULONG ContextSwitches;
    ULONG ThreadState;
    ULONG WaitReason;
} SYSTEM_THREAD_INFORMATION_EX, *PSYSTEM_THREAD_INFORMATION_EX;

// System process information
typedef struct _SYSTEM_PROCESS_INFORMATION_EX {
    ULONG NextEntryOffset;
    ULONG NumberOfThreads;
    LARGE_INTEGER WorkingSetPrivateSize;
    ULONG HardFaultCount;
    ULONG NumberOfThreadsHighWatermark;
    ULONGLONG CycleTime;
    LARGE_INTEGER CreateTime;
    LARGE_INTEGER UserTime;
    LARGE_INTEGER KernelTime;
    UNICODE_STRING ImageName;
    LONG BasePriority;
    HANDLE UniqueProcessId;
    HANDLE InheritedFromUniqueProcessId;
    ULONG HandleCount;
    ULONG SessionId;
    ULONG_PTR UniqueProcessKey;
    SIZE_T PeakVirtualSize;
    SIZE_T VirtualSize;
    ULONG PageFaultCount;
    SIZE_T PeakWorkingSetSize;
    SIZE_T WorkingSetSize;
    SIZE_T QuotaPeakPagedPoolUsage;
    SIZE_T QuotaPagedPoolUsage;
    SIZE_T QuotaPeakNonPagedPoolUsage;
    SIZE_T QuotaNonPagedPoolUsage;
    SIZE_T PagefileUsage;
    SIZE_T PeakPagefileUsage;
    SIZE_T PrivatePageCount;
    LARGE_INTEGER ReadOperationCount;
    LARGE_INTEGER WriteOperationCount;
    LARGE_INTEGER OtherOperationCount;
    LARGE_INTEGER ReadTransferCount;
    LARGE_INTEGER WriteTransferCount;
    LARGE_INTEGER OtherTransferCount;
    SYSTEM_THREAD_INFORMATION_EX Threads[1];
} SYSTEM_PROCESS_INFORMATION_EX, *PSYSTEM_PROCESS_INFORMATION_EX;

// ============================================================================
// NT API Static Imports (linked against ntdll.lib)
// ============================================================================

extern "C" {

NTSYSAPI NTSTATUS NTAPI NtAllocateVirtualMemory(
    HANDLE ProcessHandle,
    PVOID* BaseAddress,
    ULONG_PTR ZeroBits,
    PSIZE_T RegionSize,
    ULONG AllocationType,
    ULONG Protect
);

NTSYSAPI NTSTATUS NTAPI NtFreeVirtualMemory(
    HANDLE ProcessHandle,
    PVOID* BaseAddress,
    PSIZE_T RegionSize,
    ULONG FreeType
);

NTSYSAPI NTSTATUS NTAPI NtProtectVirtualMemory(
    HANDLE ProcessHandle,
    PVOID* BaseAddress,
    PSIZE_T RegionSize,
    ULONG NewProtect,
    PULONG OldProtect
);

NTSYSAPI NTSTATUS NTAPI NtFlushInstructionCache(
    HANDLE ProcessHandle,
    PVOID BaseAddress,
    SIZE_T Length
);

NTSYSAPI NTSTATUS NTAPI NtQuerySystemInformation(
    SYSTEM_INFORMATION_CLASS_EX SystemInformationClass,
    PVOID SystemInformation,
    ULONG SystemInformationLength,
    PULONG ReturnLength
);

NTSYSAPI NTSTATUS NTAPI NtOpenThread(
    PHANDLE ThreadHandle,
    ACCESS_MASK DesiredAccess,
    POBJECT_ATTRIBUTES ObjectAttributes,
    PCLIENT_ID ClientId
);

NTSYSAPI NTSTATUS NTAPI NtSuspendThread(
    HANDLE ThreadHandle,
    PULONG PreviousSuspendCount
);

NTSYSAPI NTSTATUS NTAPI NtResumeThread(
    HANDLE ThreadHandle,
    PULONG PreviousSuspendCount
);

NTSYSAPI NTSTATUS NTAPI NtClose(
    HANDLE Handle
);

} // extern "C"

// Global allocation granularity (queried once at init)
static ULONG g_AllocationGranularity = 0x10000;  // Default 64KB

// Initialize allocation granularity from system info
static void init_allocation_granularity() {
    static bool initialized = false;
    if (initialized) return;

    SYSTEM_BASIC_INFORMATION sbi = {};
    ULONG len = 0;
    if (NtQuerySystemInformation(SystemBasicInformationEx, &sbi, sizeof(sbi), &len) == STATUS_SUCCESS) {
        g_AllocationGranularity = sbi.AllocationGranularity;
    }
    initialized = true;
}

// Get current thread ID using TEB (ARM64 only)
static DWORD nt_get_current_thread_id() {
    // ARM64: TEB pointer is in x18 register
    // x18 points directly to TEB, and ClientId is at offset 0x48
    PTEB teb = reinterpret_cast<PTEB>(__getReg(18));
    return HandleToULong(teb->ClientId.UniqueThread);
}

// Get current process ID using TEB (ARM64 only)
static DWORD nt_get_current_process_id() {
    // ARM64: TEB pointer is in x18 register
    PTEB teb = reinterpret_cast<PTEB>(__getReg(18));
    return HandleToULong(teb->ClientId.UniqueProcess);
}

namespace veda64 {
namespace Hook {

// ============================================================================
// Internal structures
// ============================================================================

// Trampoline structure - holds relocated instructions + jump back
struct Trampoline {
    uint8_t* code;           // Executable memory for trampoline
    size_t code_size;        // Total allocated size
    size_t used_size;        // Actually used bytes
    size_t insn_count;       // Number of relocated instructions
};

// Hook context - complete hook state
struct HookContext {
    void* target;            // Original function address
    void* detour;            // Hook function address
    Trampoline trampoline;   // Trampoline for calling original

    uint8_t original_bytes[32];  // Saved original bytes
    uint8_t hook_bytes[32];      // Hook jump sequence
    size_t hook_size;            // Size of hook (bytes overwritten)

    bool enabled;            // Is hook currently active?
    bool valid;              // Is hook context valid?
};

// Global state
struct HookState {
    bool initialized = false;
    HookConfig config;
    std::mutex mutex;
    std::vector<HookContext*> hooks;
    std::unordered_map<void*, HookContext*> target_map;
};

static HookState g_state;

#ifndef VEDA64_NO_STRINGS
// ============================================================================
// Status to string
// ============================================================================

const char* status_to_string(HookStatus status) {
    switch (status) {
        case HookStatus::Success: return "Success";
        case HookStatus::NotInitialized: return "Hooking subsystem not initialized";
        case HookStatus::InvalidTarget: return "Invalid target address";
        case HookStatus::InvalidDetour: return "Invalid detour address";
        case HookStatus::AllocationFailed: return "Memory allocation failed";
        case HookStatus::ProtectionFailed: return "Memory protection change failed";
        case HookStatus::DisassemblyFailed: return "Instruction disassembly failed";
        case HookStatus::RelocationFailed: return "Instruction relocation failed";
        case HookStatus::InstructionTooComplex: return "Instruction too complex to relocate";
        case HookStatus::HookAlreadyInstalled: return "Hook already installed at target";
        case HookStatus::HookNotFound: return "Hook not found";
        case HookStatus::HookDisabled: return "Hook is disabled";
        case HookStatus::InternalError: return "Internal error";
        default: return "Unknown error";
    }
}
#endif // VEDA64_NO_STRINGS

// ============================================================================
// Configuration
// ============================================================================

void set_config(const HookConfig& config) {
    std::lock_guard<std::mutex> lock(g_state.mutex);
    g_state.config = config;
}

HookConfig get_config() {
    std::lock_guard<std::mutex> lock(g_state.mutex);
    return g_state.config;
}

// ============================================================================
// Initialization
// ============================================================================

HookStatus initialize() {
    std::lock_guard<std::mutex> lock(g_state.mutex);

    if (g_state.initialized) {
        return HookStatus::Success;
    }

    // Initialize allocation granularity from system info
    init_allocation_granularity();

    // Set default config
    g_state.config = HookConfig{};
    g_state.initialized = true;

    return HookStatus::Success;
}

void shutdown() {
    std::lock_guard<std::mutex> lock(g_state.mutex);

    if (!g_state.initialized) {
        return;
    }

    // Remove all hooks (unlock to avoid deadlock)
    g_state.mutex.unlock();
    remove_all();
    g_state.mutex.lock();

    g_state.initialized = false;
}

bool is_initialized() {
    std::lock_guard<std::mutex> lock(g_state.mutex);
    return g_state.initialized;
}

// ============================================================================
// Low-level memory operations (using NT syscalls)
// ============================================================================

namespace Detail {

void* alloc_executable_near(void* target, size_t size) {
    // Try to allocate RWX memory near the target for PC-relative instructions
    // We need to be within ±4GB for ADRP, ±128MB for B/BL

    uintptr_t alloc_granularity = g_AllocationGranularity;
    uintptr_t target_addr = reinterpret_cast<uintptr_t>(target);

    // Try to allocate within ±2GB of target (safe range for ADRP)
    // Search in both directions
    for (uintptr_t offset = alloc_granularity; offset < 0x7FFFFFFF; offset += alloc_granularity) {
        // Try above target
        if (target_addr + offset > target_addr) {  // Check for overflow
            PVOID base_addr = reinterpret_cast<PVOID>((target_addr + offset) & ~(alloc_granularity - 1));
            SIZE_T region_size = size;
            NTSTATUS status = NtAllocateVirtualMemory(
                NtCurrentProcess(),
                &base_addr,
                0,
                &region_size,
                MEM_COMMIT | MEM_RESERVE,
                PAGE_EXECUTE_READWRITE
            );
            if (status == STATUS_SUCCESS) return base_addr;
        }

        // Try below target
        if (target_addr > offset) {  // Check for underflow
            PVOID base_addr = reinterpret_cast<PVOID>((target_addr - offset) & ~(alloc_granularity - 1));
            SIZE_T region_size = size;
            NTSTATUS status = NtAllocateVirtualMemory(
                NtCurrentProcess(),
                &base_addr,
                0,
                &region_size,
                MEM_COMMIT | MEM_RESERVE,
                PAGE_EXECUTE_READWRITE
            );
            if (status == STATUS_SUCCESS) return base_addr;
        }
    }

    // Fall back to any location
    PVOID base_addr = nullptr;
    SIZE_T region_size = size;
    NTSTATUS status = NtAllocateVirtualMemory(
        NtCurrentProcess(),
        &base_addr,
        0,
        &region_size,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_EXECUTE_READWRITE
    );
    return (status == STATUS_SUCCESS) ? base_addr : nullptr;
}

void* alloc_executable(size_t size) {
    // Standard allocation (may be far from target)
    PVOID base_addr = nullptr;
    SIZE_T region_size = size;
    NTSTATUS status = NtAllocateVirtualMemory(
        NtCurrentProcess(),
        &base_addr,
        0,
        &region_size,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_EXECUTE_READWRITE
    );
    return (status == STATUS_SUCCESS) ? base_addr : nullptr;
}

void free_executable(void* ptr, size_t /* size */) {
    if (ptr) {
        PVOID base_addr = ptr;
        SIZE_T region_size = 0;
        NtFreeVirtualMemory(NtCurrentProcess(), &base_addr, &region_size, MEM_RELEASE);
    }
}

uint32_t make_writable(void* addr, size_t size) {
    PVOID base_addr = addr;
    SIZE_T region_size = size;
    ULONG old_protect = 0;
    NtProtectVirtualMemory(NtCurrentProcess(), &base_addr, &region_size, PAGE_EXECUTE_READWRITE, &old_protect);
    return static_cast<uint32_t>(old_protect);
}

void restore_protection(void* addr, size_t size, uint32_t old_protect) {
    PVOID base_addr = addr;
    SIZE_T region_size = size;
    ULONG dummy = 0;
    NtProtectVirtualMemory(NtCurrentProcess(), &base_addr, &region_size, static_cast<ULONG>(old_protect), &dummy);
}

void flush_icache(void* addr, size_t size) {
    NtFlushInstructionCache(NtCurrentProcess(), addr, size);
}

void suspend_threads() {
    DWORD current_tid = nt_get_current_thread_id();
    DWORD pid = nt_get_current_process_id();

    // Query process/thread information using NtQuerySystemInformation
    ULONG buffer_size = 1024 * 1024;  // Start with 1MB
    std::vector<BYTE> buffer(buffer_size);
    ULONG return_length = 0;

    NTSTATUS status;
    while ((status = NtQuerySystemInformation(
        SystemProcessInformationEx,
        buffer.data(),
        static_cast<ULONG>(buffer.size()),
        &return_length)) == STATUS_INFO_LENGTH_MISMATCH) {
        buffer.resize(return_length + 4096);
    }

    if (status != STATUS_SUCCESS) {
        return;
    }

    // Find our process and enumerate its threads
    PSYSTEM_PROCESS_INFORMATION_EX proc_info = reinterpret_cast<PSYSTEM_PROCESS_INFORMATION_EX>(buffer.data());
    while (true) {
        if (HandleToULong(proc_info->UniqueProcessId) == pid) {
            // Found our process, enumerate threads
            for (ULONG i = 0; i < proc_info->NumberOfThreads; ++i) {
                DWORD tid = HandleToULong(proc_info->Threads[i].ClientId.UniqueThread);
                if (tid != current_tid) {
                    // Open and suspend this thread
                    HANDLE thread_handle = nullptr;
                    OBJECT_ATTRIBUTES obj_attr;
                    CLIENT_ID client_id;
                    client_id.UniqueProcess = nullptr;
                    client_id.UniqueThread = ULongToHandle(tid);
                    InitializeObjectAttributes(&obj_attr, nullptr, 0, nullptr, nullptr);

                    if (NtOpenThread(&thread_handle, THREAD_SUSPEND_RESUME, &obj_attr, &client_id) == STATUS_SUCCESS) {
                        NtSuspendThread(thread_handle, nullptr);
                        NtClose(thread_handle);
                    }
                }
            }
            break;
        }

        if (proc_info->NextEntryOffset == 0) break;
        proc_info = reinterpret_cast<PSYSTEM_PROCESS_INFORMATION_EX>(
            reinterpret_cast<BYTE*>(proc_info) + proc_info->NextEntryOffset);
    }
}

void resume_threads() {
    DWORD current_tid = nt_get_current_thread_id();
    DWORD pid = nt_get_current_process_id();

    // Query process/thread information using NtQuerySystemInformation
    ULONG buffer_size = 1024 * 1024;  // Start with 1MB
    std::vector<BYTE> buffer(buffer_size);
    ULONG return_length = 0;

    NTSTATUS status;
    while ((status = NtQuerySystemInformation(
        SystemProcessInformationEx,
        buffer.data(),
        static_cast<ULONG>(buffer.size()),
        &return_length)) == STATUS_INFO_LENGTH_MISMATCH) {
        buffer.resize(return_length + 4096);
    }

    if (status != STATUS_SUCCESS) {
        return;
    }

    // Find our process and enumerate its threads
    PSYSTEM_PROCESS_INFORMATION_EX proc_info = reinterpret_cast<PSYSTEM_PROCESS_INFORMATION_EX>(buffer.data());
    while (true) {
        if (HandleToULong(proc_info->UniqueProcessId) == pid) {
            // Found our process, enumerate threads
            for (ULONG i = 0; i < proc_info->NumberOfThreads; ++i) {
                DWORD tid = HandleToULong(proc_info->Threads[i].ClientId.UniqueThread);
                if (tid != current_tid) {
                    // Open and resume this thread
                    HANDLE thread_handle = nullptr;
                    OBJECT_ATTRIBUTES obj_attr;
                    CLIENT_ID client_id;
                    client_id.UniqueProcess = nullptr;
                    client_id.UniqueThread = ULongToHandle(tid);
                    InitializeObjectAttributes(&obj_attr, nullptr, 0, nullptr, nullptr);

                    if (NtOpenThread(&thread_handle, THREAD_SUSPEND_RESUME, &obj_attr, &client_id) == STATUS_SUCCESS) {
                        NtResumeThread(thread_handle, nullptr);
                        NtClose(thread_handle);
                    }
                }
            }
            break;
        }

        if (proc_info->NextEntryOffset == 0) break;
        proc_info = reinterpret_cast<PSYSTEM_PROCESS_INFORMATION_EX>(
            reinterpret_cast<BYTE*>(proc_info) + proc_info->NextEntryOffset);
    }
}

// ============================================================================
// ARM64 instruction analysis and generation
// ============================================================================

// ARM64 jump sequence using LDR + BR (16 bytes total)
// LDR X16, [PC, #8]   ; 0x58000050
// BR X16              ; 0xD61F0200
// .quad target        ; 8 bytes for address
size_t generate_jump(uint8_t* buffer, void* target) {
    uint32_t* insn = reinterpret_cast<uint32_t*>(buffer);

    // LDR X16, [PC, #8] - load address from 8 bytes ahead
    insn[0] = 0x58000050;

    // BR X16 - branch to register
    insn[1] = 0xD61F0200;

    // 64-bit target address
    uint64_t* addr = reinterpret_cast<uint64_t*>(&insn[2]);
    *addr = reinterpret_cast<uint64_t>(target);

    return 16;
}

// ARM64 call sequence using LDR + BLR (16 bytes, returns to next insn)
size_t generate_call(uint8_t* buffer, void* target) {
    uint32_t* insn = reinterpret_cast<uint32_t*>(buffer);

    // LDR X16, [PC, #8] - load address from 8 bytes ahead
    insn[0] = 0x58000050;

    // BLR X16 - branch with link to register
    insn[1] = 0xD63F0200;

    // 64-bit target address
    uint64_t* addr = reinterpret_cast<uint64_t*>(&insn[2]);
    *addr = reinterpret_cast<uint64_t>(target);

    return 16;
}

// Check if instruction is PC-relative
bool is_pc_relative(uint32_t insn) {
    // Use veda64 to decode the instruction
    auto decoded = decode(insn);
    if (!decoded) {
        return false;
    }

    // Check for PC-relative instruction classes:
    // - B, BL (unconditional branch)
    // - B.cond (conditional branch)
    // - CBZ, CBNZ (compare and branch)
    // - TBZ, TBNZ (test and branch)
    // - ADR, ADRP (address calculation)
    // - LDR (literal) - loads from PC-relative address

    switch (decoded->mnemonic) {
        // Unconditional branches
        case Mnemonic::B:
        case Mnemonic::BL:
        // Conditional branches (B.cond is encoded as BC in ARM64)
        case Mnemonic::BC:
        // Compare and branch
        case Mnemonic::CBZ:
        case Mnemonic::CBNZ:
        // Test and branch
        case Mnemonic::TBZ:
        case Mnemonic::TBNZ:
        // Address calculation
        case Mnemonic::ADR:
        case Mnemonic::ADRP:
            return true;

        // LDR literal - check for PC-relative form
        case Mnemonic::LDR:
        case Mnemonic::LDRSW:
        case Mnemonic::PRFM:
            // PC-relative if has relative operand
            for (const auto& op : decoded->operands) {
                if (op.type == OperandType::Relative) {
                    return true;
                }
            }
            return false;

        default:
            return false;
    }
}

// Check if instruction can be safely relocated
bool can_relocate(uint32_t insn) {
    auto decoded = decode(insn);
    if (!decoded) {
        return false;
    }

    // Most instructions can be relocated
    // Exceptions:
    // - Instructions that read PC directly (rare on ARM64)
    // - Some system instructions

    switch (decoded->mnemonic) {
        // These are generally safe even if PC-relative (we handle them)
        case Mnemonic::B:
        case Mnemonic::BL:
        case Mnemonic::BC:
        case Mnemonic::CBZ:
        case Mnemonic::CBNZ:
        case Mnemonic::TBZ:
        case Mnemonic::TBNZ:
        case Mnemonic::ADR:
        case Mnemonic::ADRP:
        case Mnemonic::LDR:
        case Mnemonic::LDRSW:
            return true;

        // Return instructions - can't relocate
        case Mnemonic::RET:
        case Mnemonic::RETAA:
        case Mnemonic::RETAB:
        case Mnemonic::ERET:
        case Mnemonic::ERETAA:
        case Mnemonic::ERETAB:
            return false;

        default:
            // Most other instructions are position-independent
            return true;
    }
}

// Relocate a single instruction
bool relocate_instruction(
    uint32_t insn,
    uint64_t old_pc,
    uint64_t new_pc,
    uint32_t* out_insn,
    size_t* out_count
) {
    auto decoded = decode(insn);
    if (!decoded) {
        *out_count = 0;
        return false;
    }

    // If not PC-relative, just copy the instruction
    if (!is_pc_relative(insn)) {
        out_insn[0] = insn;
        *out_count = 1;
        return true;
    }

    // Handle PC-relative instructions
    switch (decoded->mnemonic) {
        case Mnemonic::B:
        case Mnemonic::BL: {
            // B/BL imm26 - 26-bit signed offset * 4
            int32_t imm26 = static_cast<int32_t>(insn & 0x03FFFFFF);
            if (imm26 & 0x02000000) {  // Sign extend
                imm26 |= 0xFC000000;
            }
            int64_t offset = static_cast<int64_t>(imm26) * 4;
            uint64_t target = old_pc + offset;

            // Calculate new offset
            int64_t new_offset = static_cast<int64_t>(target - new_pc);

            // Check if within range (±128MB)
            if (new_offset >= -134217728 && new_offset <= 134217724 && (new_offset & 3) == 0) {
                // Can use direct branch
                uint32_t new_imm26 = static_cast<uint32_t>((new_offset / 4) & 0x03FFFFFF);
                out_insn[0] = (insn & 0xFC000000) | new_imm26;
                *out_count = 1;
                return true;
            }

            // Need to use indirect branch sequence
            // This is more complex - for now, return failure
            *out_count = 0;
            return false;
        }

        case Mnemonic::BC: {
            // B.cond imm19 - 19-bit signed offset * 4
            int32_t imm19 = static_cast<int32_t>((insn >> 5) & 0x7FFFF);
            if (imm19 & 0x40000) {  // Sign extend
                imm19 |= 0xFFF80000;
            }
            int64_t offset = static_cast<int64_t>(imm19) * 4;
            uint64_t target = old_pc + offset;

            int64_t new_offset = static_cast<int64_t>(target - new_pc);

            // Check if within range (±1MB)
            if (new_offset >= -1048576 && new_offset <= 1048572 && (new_offset & 3) == 0) {
                uint32_t new_imm19 = static_cast<uint32_t>((new_offset / 4) & 0x7FFFF);
                out_insn[0] = (insn & 0xFF00001F) | (new_imm19 << 5);
                *out_count = 1;
                return true;
            }

            *out_count = 0;
            return false;
        }

        case Mnemonic::CBZ:
        case Mnemonic::CBNZ: {
            // CBZ/CBNZ imm19 - 19-bit signed offset * 4
            int32_t imm19 = static_cast<int32_t>((insn >> 5) & 0x7FFFF);
            if (imm19 & 0x40000) {
                imm19 |= 0xFFF80000;
            }
            int64_t offset = static_cast<int64_t>(imm19) * 4;
            uint64_t target = old_pc + offset;

            int64_t new_offset = static_cast<int64_t>(target - new_pc);

            if (new_offset >= -1048576 && new_offset <= 1048572 && (new_offset & 3) == 0) {
                uint32_t new_imm19 = static_cast<uint32_t>((new_offset / 4) & 0x7FFFF);
                out_insn[0] = (insn & 0xFF00001F) | (new_imm19 << 5);
                *out_count = 1;
                return true;
            }

            *out_count = 0;
            return false;
        }

        case Mnemonic::TBZ:
        case Mnemonic::TBNZ: {
            // TBZ/TBNZ imm14 - 14-bit signed offset * 4
            int32_t imm14 = static_cast<int32_t>((insn >> 5) & 0x3FFF);
            if (imm14 & 0x2000) {
                imm14 |= 0xFFFFC000;
            }
            int64_t offset = static_cast<int64_t>(imm14) * 4;
            uint64_t target = old_pc + offset;

            int64_t new_offset = static_cast<int64_t>(target - new_pc);

            // Check if within range (±32KB)
            if (new_offset >= -32768 && new_offset <= 32764 && (new_offset & 3) == 0) {
                uint32_t new_imm14 = static_cast<uint32_t>((new_offset / 4) & 0x3FFF);
                out_insn[0] = (insn & 0xFFF8001F) | (new_imm14 << 5);
                *out_count = 1;
                return true;
            }

            *out_count = 0;
            return false;
        }

        case Mnemonic::ADR: {
            // ADR Xd, label - 21-bit signed offset
            uint32_t immlo = (insn >> 29) & 0x3;
            uint32_t immhi = (insn >> 5) & 0x7FFFF;
            int32_t imm21 = static_cast<int32_t>((immhi << 2) | immlo);
            if (imm21 & 0x100000) {
                imm21 |= 0xFFE00000;
            }
            uint64_t target = old_pc + imm21;

            int64_t new_offset = static_cast<int64_t>(target - new_pc);

            // Check if within range (±1MB)
            if (new_offset >= -1048576 && new_offset <= 1048575) {
                uint32_t new_imm21 = static_cast<uint32_t>(new_offset) & 0x1FFFFF;
                uint32_t new_immlo = new_imm21 & 0x3;
                uint32_t new_immhi = (new_imm21 >> 2) & 0x7FFFF;
                out_insn[0] = (insn & 0x9F00001F) | (new_immlo << 29) | (new_immhi << 5);
                *out_count = 1;
                return true;
            }

            *out_count = 0;
            return false;
        }

        case Mnemonic::ADRP: {
            // ADRP Xd, label - page-aligned address
            uint32_t immlo = (insn >> 29) & 0x3;
            uint32_t immhi = (insn >> 5) & 0x7FFFF;
            int32_t imm21 = static_cast<int32_t>((immhi << 2) | immlo);
            if (imm21 & 0x100000) {
                imm21 |= 0xFFE00000;
            }
            int64_t offset = static_cast<int64_t>(imm21) << 12;
            uint64_t target = (old_pc & ~0xFFFULL) + offset;

            int64_t new_offset = static_cast<int64_t>(target - (new_pc & ~0xFFFULL));

            // Check if within range (±4GB pages)
            if (new_offset >= -4294967296LL && new_offset <= 4294963200LL) {
                int32_t new_imm21 = static_cast<int32_t>(new_offset >> 12);
                uint32_t new_immlo = new_imm21 & 0x3;
                uint32_t new_immhi = (new_imm21 >> 2) & 0x7FFFF;
                out_insn[0] = (insn & 0x9F00001F) | (new_immlo << 29) | (new_immhi << 5);
                *out_count = 1;
                return true;
            }

            *out_count = 0;
            return false;
        }

        default:
            // For other PC-relative instructions (LDR literal, etc.)
            // we'd need more complex handling
            out_insn[0] = insn;
            *out_count = 1;
            return true;
    }
}

} // namespace Detail

// ============================================================================
// Hook installation
// ============================================================================

static Trampoline create_trampoline(void* target, size_t hook_size, HookStatus* status) {
    Trampoline tramp = {};

    // Allocate space for relocated instructions + jump back
    // Each instruction might expand to multiple instructions during relocation
    size_t max_size = (hook_size / 4) * 16 + 16;  // Worst case expansion + jump

    // Allocate near the target for PC-relative instruction relocation
    tramp.code = static_cast<uint8_t*>(Detail::alloc_executable_near(target, max_size));
    if (!tramp.code) {
        *status = HookStatus::AllocationFailed;
        return tramp;
    }
    tramp.code_size = max_size;

    // Disassemble and relocate instructions
    uint8_t* src = static_cast<uint8_t*>(target);
    uint8_t* dst = tramp.code;
    size_t src_offset = 0;
    size_t dst_offset = 0;
    uint64_t src_pc = reinterpret_cast<uint64_t>(target);
    uint64_t dst_pc = reinterpret_cast<uint64_t>(tramp.code);

    while (src_offset < hook_size) {
        uint32_t insn = *reinterpret_cast<uint32_t*>(src + src_offset);

        // Check if we can relocate this instruction
        if (!Detail::can_relocate(insn)) {
            *status = HookStatus::InstructionTooComplex;
            Detail::free_executable(tramp.code, tramp.code_size);
            tramp.code = nullptr;
            return tramp;
        }

        // Relocate the instruction
        uint32_t relocated[4];
        size_t relocated_count = 0;

        if (!Detail::relocate_instruction(
            insn,
            src_pc + src_offset,
            dst_pc + dst_offset,
            relocated,
            &relocated_count
        )) {
            *status = HookStatus::RelocationFailed;
            Detail::free_executable(tramp.code, tramp.code_size);
            tramp.code = nullptr;
            return tramp;
        }

        // Copy relocated instructions to trampoline
        for (size_t i = 0; i < relocated_count; ++i) {
            *reinterpret_cast<uint32_t*>(dst + dst_offset) = relocated[i];
            dst_offset += 4;
        }

        src_offset += 4;
        tramp.insn_count++;
    }

    // Add jump back to original code after hook
    void* return_addr = static_cast<uint8_t*>(target) + hook_size;
    dst_offset += Detail::generate_jump(dst + dst_offset, return_addr);

    tramp.used_size = dst_offset;

    // Flush instruction cache for trampoline
    Detail::flush_icache(tramp.code, tramp.used_size);

    *status = HookStatus::Success;
    return tramp;
}

HookHandle install_ex(void* target, void* detour, void** original, HookStatus* status) {
    if (!g_state.initialized) {
        *status = HookStatus::NotInitialized;
        return nullptr;
    }

    if (!target) {
        *status = HookStatus::InvalidTarget;
        return nullptr;
    }

    if (!detour) {
        *status = HookStatus::InvalidDetour;
        return nullptr;
    }

    std::lock_guard<std::mutex> lock(g_state.mutex);

    // Check if already hooked
    if (g_state.target_map.find(target) != g_state.target_map.end()) {
        if (!g_state.config.allow_chain) {
            *status = HookStatus::HookAlreadyInstalled;
            return nullptr;
        }
    }

    // Create hook context
    HookContext* ctx = new HookContext{};
    ctx->target = target;
    ctx->detour = detour;
    ctx->hook_size = g_state.config.min_hook_size;
    ctx->enabled = false;
    ctx->valid = false;

    // Round up hook size to instruction boundary
    if (ctx->hook_size % 4 != 0) {
        ctx->hook_size = ((ctx->hook_size / 4) + 1) * 4;
    }

    // Ensure minimum size for jump sequence (16 bytes)
    if (ctx->hook_size < 16) {
        ctx->hook_size = 16;
    }

    // Save original bytes
    std::memcpy(ctx->original_bytes, target, ctx->hook_size);

    // Create trampoline
    ctx->trampoline = create_trampoline(target, ctx->hook_size, status);
    if (!ctx->trampoline.code) {
        delete ctx;
        return nullptr;
    }

    // Generate hook jump sequence
    Detail::generate_jump(ctx->hook_bytes, detour);

    // Install hook
    if (g_state.config.thread_safe) {
        Detail::suspend_threads();
    }

    uint32_t old_protect = Detail::make_writable(target, ctx->hook_size);
    std::memcpy(target, ctx->hook_bytes, ctx->hook_size);
    Detail::restore_protection(target, ctx->hook_size, old_protect);
    Detail::flush_icache(target, ctx->hook_size);

    if (g_state.config.thread_safe) {
        Detail::resume_threads();
    }

    ctx->enabled = true;
    ctx->valid = true;

    // Store hook in global state
    g_state.hooks.push_back(ctx);
    g_state.target_map[target] = ctx;

    // Return trampoline as original function pointer
    if (original) {
        *original = ctx->trampoline.code;
    }

    *status = HookStatus::Success;
    return ctx;
}

HookHandle install(void* target, void* detour, void** original) {
    HookStatus status;
    return install_ex(target, detour, original, &status);
}

// ============================================================================
// Hook removal
// ============================================================================

HookStatus remove(HookHandle handle) {
    if (!g_state.initialized) {
        return HookStatus::NotInitialized;
    }

    if (!handle || !handle->valid) {
        return HookStatus::HookNotFound;
    }

    std::lock_guard<std::mutex> lock(g_state.mutex);

    // Find and validate hook
    auto it = std::find(g_state.hooks.begin(), g_state.hooks.end(), handle);
    if (it == g_state.hooks.end()) {
        return HookStatus::HookNotFound;
    }

    HookContext* ctx = handle;

    // Restore original bytes
    if (ctx->enabled) {
        if (g_state.config.thread_safe) {
            Detail::suspend_threads();
        }

        uint32_t old_protect = Detail::make_writable(ctx->target, ctx->hook_size);
        std::memcpy(ctx->target, ctx->original_bytes, ctx->hook_size);
        Detail::restore_protection(ctx->target, ctx->hook_size, old_protect);
        Detail::flush_icache(ctx->target, ctx->hook_size);

        if (g_state.config.thread_safe) {
            Detail::resume_threads();
        }
    }

    // Free trampoline
    if (ctx->trampoline.code) {
        Detail::free_executable(ctx->trampoline.code, ctx->trampoline.code_size);
    }

    // Remove from global state
    g_state.target_map.erase(ctx->target);
    g_state.hooks.erase(it);

    // Delete context
    ctx->valid = false;
    delete ctx;

    return HookStatus::Success;
}

void remove_all() {
    if (!g_state.initialized) {
        return;
    }

    std::lock_guard<std::mutex> lock(g_state.mutex);

    // Copy hook list (remove modifies it)
    std::vector<HookContext*> hooks_copy = g_state.hooks;

    g_state.mutex.unlock();
    for (auto* ctx : hooks_copy) {
        remove(ctx);
    }
    g_state.mutex.lock();
}

// ============================================================================
// Hook enable/disable
// ============================================================================

HookStatus enable(HookHandle handle) {
    if (!g_state.initialized) {
        return HookStatus::NotInitialized;
    }

    if (!handle || !handle->valid) {
        return HookStatus::HookNotFound;
    }

    std::lock_guard<std::mutex> lock(g_state.mutex);

    if (handle->enabled) {
        return HookStatus::Success;
    }

    // Install hook bytes
    if (g_state.config.thread_safe) {
        Detail::suspend_threads();
    }

    uint32_t old_protect = Detail::make_writable(handle->target, handle->hook_size);
    std::memcpy(handle->target, handle->hook_bytes, handle->hook_size);
    Detail::restore_protection(handle->target, handle->hook_size, old_protect);
    Detail::flush_icache(handle->target, handle->hook_size);

    if (g_state.config.thread_safe) {
        Detail::resume_threads();
    }

    handle->enabled = true;
    return HookStatus::Success;
}

HookStatus disable(HookHandle handle) {
    if (!g_state.initialized) {
        return HookStatus::NotInitialized;
    }

    if (!handle || !handle->valid) {
        return HookStatus::HookNotFound;
    }

    std::lock_guard<std::mutex> lock(g_state.mutex);

    if (!handle->enabled) {
        return HookStatus::Success;
    }

    // Restore original bytes
    if (g_state.config.thread_safe) {
        Detail::suspend_threads();
    }

    uint32_t old_protect = Detail::make_writable(handle->target, handle->hook_size);
    std::memcpy(handle->target, handle->original_bytes, handle->hook_size);
    Detail::restore_protection(handle->target, handle->hook_size, old_protect);
    Detail::flush_icache(handle->target, handle->hook_size);

    if (g_state.config.thread_safe) {
        Detail::resume_threads();
    }

    handle->enabled = false;
    return HookStatus::Success;
}

bool is_enabled(HookHandle handle) {
    if (!handle || !handle->valid) {
        return false;
    }
    return handle->enabled;
}

// ============================================================================
// Hook information
// ============================================================================

void* get_target(HookHandle handle) {
    if (!handle || !handle->valid) return nullptr;
    return handle->target;
}

void* get_detour(HookHandle handle) {
    if (!handle || !handle->valid) return nullptr;
    return handle->detour;
}

void* get_trampoline(HookHandle handle) {
    if (!handle || !handle->valid) return nullptr;
    return handle->trampoline.code;
}

size_t get_hook_size(HookHandle handle) {
    if (!handle || !handle->valid) return 0;
    return handle->hook_size;
}

size_t get_relocated_count(HookHandle handle) {
    if (!handle || !handle->valid) return 0;
    return handle->trampoline.insn_count;
}

#ifndef VEDA64_NO_STRINGS
void dump_hook(HookHandle handle) {
    if (!handle || !handle->valid) {
        printf("Invalid hook handle\n");
        return;
    }

    printf("Hook Information:\n");
    printf("  Target:      %p\n", handle->target);
    printf("  Detour:      %p\n", handle->detour);
    printf("  Trampoline:  %p\n", handle->trampoline.code);
    printf("  Hook size:   %zu bytes\n", handle->hook_size);
    printf("  Relocated:   %zu instructions\n", handle->trampoline.insn_count);
    printf("  Enabled:     %s\n", handle->enabled ? "yes" : "no");

    printf("  Original bytes: ");
    for (size_t i = 0; i < handle->hook_size; ++i) {
        printf("%02X ", handle->original_bytes[i]);
    }
    printf("\n");

    printf("  Hook bytes:     ");
    for (size_t i = 0; i < handle->hook_size; ++i) {
        printf("%02X ", handle->hook_bytes[i]);
    }
    printf("\n");

    // Disassemble original instructions
    printf("  Original instructions:\n");
    uint32_t* insns = reinterpret_cast<uint32_t*>(handle->original_bytes);
    for (size_t i = 0; i < handle->hook_size / 4; ++i) {
        auto decoded = decode(insns[i]);
        if (decoded) {
            printf("    %08X: %s\n", insns[i], decoded->to_string().c_str());
        } else {
            printf("    %08X: <unknown>\n", insns[i]);
        }
    }

    // Disassemble trampoline
    printf("  Trampoline instructions:\n");
    insns = reinterpret_cast<uint32_t*>(handle->trampoline.code);
    for (size_t i = 0; i < handle->trampoline.used_size / 4; ++i) {
        auto decoded = decode(insns[i]);
        if (decoded) {
            printf("    %08X: %s\n", insns[i], decoded->to_string().c_str());
        } else {
            printf("    %08X: <unknown>\n", insns[i]);
        }
    }
}
#endif // !VEDA64_NO_STRINGS

} // namespace Hook
} // namespace veda64

#endif // _WIN32 || VEDA64_HOOK_SUPPORT
