// Auto-generated IR builder functions for dpimm
// Do not edit - generated by parse_arm64_xml.py
#include "ir.hpp"

namespace veda64 {
namespace ir {

Tree build_ir_ADD_32_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADD_32_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "-"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::ident("operand2"), ir::bit_lit("0")})));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_ADD_64_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADD_64_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "-"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::ident("operand2"), ir::bit_lit("0")})));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_ADDG_64_addsub_immtags(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADDG_64_addsub_immtags";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_MTE")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("tag_offset", "bits(4)", ir::ident("imm4")));
        stmts.push_back(ir::let_decl("offset", "bits(64)", ir::func_call("LSL", {}, {ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("imm6")}), ir::ident("LOG2_TAG_GRANULE")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(64)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("X", {ir::int_lit(64)}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("start_tag", "bits(4)", ir::func_call("AArch64_AllocationTagFromAddress", {}, {ir::ident("operand1")})));
        stmts.push_back(ir::let_decl("exclude", "bits(16)", ir::field_access(ir::func_call("GCR_EL1", {}, {}), "Exclude")));
        stmts.push_back(ir::let_decl("rtag", "bits(4)", ir::func_call("AArch64_ChooseNonExcludedTagOrZero", {}, {ir::ident("start_tag"), ir::ident("tag_offset"), ir::ident("exclude")})));
        stmts.push_back(ir::var_decl("result", "bits(64)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "-"}, ir::func_call("AddWithCarry", {ir::int_lit(64)}, {ir::ident("operand1"), ir::ident("offset"), ir::bit_lit("0")})));
        stmts.push_back(ir::assign(ir::ident("result"), ir::func_call("AArch64_AddressWithAllocationTag", {}, {ir::ident("result"), ir::ident("rtag")})));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::ident("result")));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_ADDS_32S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADDS_32S_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("nzcv", "bits(4)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "nzcv"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::ident("operand2"), ir::bit_lit("0")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
        stmts.push_back(ir::assign(ir::field_access_multi(ir::ident("PSTATE"), {"N", "Z", "C", "V"}), ir::ident("nzcv")));
    }

    return tree;
}

Tree build_ir_ADDS_64S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADDS_64S_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("nzcv", "bits(4)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "nzcv"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::ident("operand2"), ir::bit_lit("0")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
        stmts.push_back(ir::assign(ir::field_access_multi(ir::ident("PSTATE"), {"N", "Z", "C", "V"}), ir::ident("nzcv")));
    }

    return tree;
}

Tree build_ir_ADR_only_pcreladdr(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADR_only_pcreladdr";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("imm", "bits(64)", ir::func_call("SignExtend", {}, {ir::bit_concat({ir::ident("immhi"), ir::ident("immlo")})})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::assign(ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::bin_op("+", ir::func_call("PC64", {}, {}), ir::ident("imm"))));
    }

    return tree;
}

Tree build_ir_ADRP_only_pcreladdr(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ADRP_only_pcreladdr";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("imm", "bits(64)", ir::func_call("SignExtend", {}, {ir::bit_concat({ir::ident("immhi"), ir::ident("immlo"), ir::func_call("Zeros", {ir::int_lit(12)}, {})})})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("base", "bits(64)", ir::bit_concat({ir::bit_slice(ir::func_call("PC64", {}, {}), ir::int_lit(63), ir::int_lit(12), false), ir::func_call("Zeros", {ir::int_lit(12)}, {})})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::bin_op("+", ir::ident("base"), ir::ident("imm"))));
    }

    return tree;
}

Tree build_ir_AND_32_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "AND_32_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("AND", ir::ident("operand1"), ir::ident("operand2"))));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_AND_64_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "AND_64_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("AND", ir::ident("operand1"), ir::ident("operand2"))));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_ANDS_32S_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ANDS_32S_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("AND", ir::ident("operand1"), ir::ident("operand2"))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
        stmts.push_back(ir::assign(ir::field_access_multi(ir::ident("PSTATE"), {"N", "Z", "C", "V"}), ir::bit_concat({ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), false), ir::func_call("IsZeroBit", {ir::ident("datasize")}, {ir::ident("result")}), ir::bit_lit("00")})));
    }

    return tree;
}

Tree build_ir_ANDS_64S_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ANDS_64S_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("AND", ir::ident("operand1"), ir::ident("operand2"))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
        stmts.push_back(ir::assign(ir::field_access_multi(ir::ident("PSTATE"), {"N", "Z", "C", "V"}), ir::bit_concat({ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), false), ir::func_call("IsZeroBit", {ir::ident("datasize")}, {ir::ident("result")}), ir::bit_lit("00")})));
    }

    return tree;
}

Tree build_ir_ASR_SBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ASR_SBFM_32M_bitfield";


    return tree;
}

Tree build_ir_ASR_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ASR_SBFM_64M_bitfield";


    return tree;
}

Tree build_ir_AUTIASPPC_only_dp_1src_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "AUTIASPPC_only_dp_1src_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_PAuth_LR")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::int_lit(30)));
        stmts.push_back(ir::let_decl("offset", "bits(64)", ir::func_call("ZeroExtend", {}, {ir::bit_concat({ir::ident("imm16"), ir::bit_lit("00")})})));
        stmts.push_back(ir::let_decl("auth_combined", "boolean", ir::bool_lit(false)));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("pac_addr", "bits(64)", ir::bin_op("-", ir::func_call("PC64", {}, {}), ir::ident("offset"))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::func_call("AuthIA2", {}, {ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::func_call("SP", {ir::int_lit(64)}, {}), ir::ident("pac_addr"), ir::ident("auth_combined")})));
    }

    return tree;
}

Tree build_ir_AUTIBSPPC_only_dp_1src_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "AUTIBSPPC_only_dp_1src_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_PAuth_LR")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::int_lit(30)));
        stmts.push_back(ir::let_decl("offset", "bits(64)", ir::func_call("ZeroExtend", {}, {ir::bit_concat({ir::ident("imm16"), ir::bit_lit("00")})})));
        stmts.push_back(ir::let_decl("auth_combined", "boolean", ir::bool_lit(false)));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("pac_addr", "bits(64)", ir::bin_op("-", ir::func_call("PC64", {}, {}), ir::ident("offset"))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::func_call("AuthIB2", {}, {ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::func_call("SP", {ir::int_lit(64)}, {}), ir::ident("pac_addr"), ir::ident("auth_combined")})));
    }

    return tree;
}

Tree build_ir_BFC_BFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFC_BFM_32M_bitfield";


    return tree;
}

Tree build_ir_BFC_BFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFC_BFM_64M_bitfield";


    return tree;
}

Tree build_ir_BFI_BFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFI_BFM_32M_bitfield";


    return tree;
}

Tree build_ir_BFI_BFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFI_BFM_64M_bitfield";


    return tree;
}

Tree build_ir_BFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFM_32M_bitfield";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("1")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("||", ir::bin_op("||", ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0")), ir::bin_op("!=", ir::bit_slice(ir::ident("immr"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0"))), ir::bin_op("!=", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0")))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("s", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
        stmts.push_back(ir::let_decl("r", "integer", ir::func_call("UInt", {}, {ir::ident("immr")})));
        stmts.push_back(ir::var_decl("wmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("tmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"wmask", "tmask"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(false)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("dst", "bits(datasize)", ir::func_call("X", {}, {ir::ident("d")})));
        stmts.push_back(ir::let_decl("src", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("bot", "bits(datasize)", ir::bin_op("OR", ir::bin_op("AND", ir::ident("dst"), ir::unary_op("NOT", ir::ident("wmask"))), ir::bin_op("AND", ir::func_call("ROR", {}, {ir::ident("src"), ir::ident("r")}), ir::ident("wmask")))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bin_op("OR", ir::bin_op("AND", ir::ident("dst"), ir::unary_op("NOT", ir::ident("tmask"))), ir::bin_op("AND", ir::ident("bot"), ir::ident("tmask")))));
    }

    return tree;
}

Tree build_ir_BFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFM_64M_bitfield";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("1")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("||", ir::bin_op("||", ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0")), ir::bin_op("!=", ir::bit_slice(ir::ident("immr"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0"))), ir::bin_op("!=", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0")))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("s", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
        stmts.push_back(ir::let_decl("r", "integer", ir::func_call("UInt", {}, {ir::ident("immr")})));
        stmts.push_back(ir::var_decl("wmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("tmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"wmask", "tmask"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(false)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("dst", "bits(datasize)", ir::func_call("X", {}, {ir::ident("d")})));
        stmts.push_back(ir::let_decl("src", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("bot", "bits(datasize)", ir::bin_op("OR", ir::bin_op("AND", ir::ident("dst"), ir::unary_op("NOT", ir::ident("wmask"))), ir::bin_op("AND", ir::func_call("ROR", {}, {ir::ident("src"), ir::ident("r")}), ir::ident("wmask")))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bin_op("OR", ir::bin_op("AND", ir::ident("dst"), ir::unary_op("NOT", ir::ident("tmask"))), ir::bin_op("AND", ir::ident("bot"), ir::ident("tmask")))));
    }

    return tree;
}

Tree build_ir_BFXIL_BFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFXIL_BFM_32M_bitfield";


    return tree;
}

Tree build_ir_BFXIL_BFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "BFXIL_BFM_64M_bitfield";


    return tree;
}

Tree build_ir_CMN_ADDS_32S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "CMN_ADDS_32S_addsub_imm";


    return tree;
}

Tree build_ir_CMN_ADDS_64S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "CMN_ADDS_64S_addsub_imm";


    return tree;
}

Tree build_ir_CMP_SUBS_32S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "CMP_SUBS_32S_addsub_imm";


    return tree;
}

Tree build_ir_CMP_SUBS_64S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "CMP_SUBS_64S_addsub_imm";


    return tree;
}

Tree build_ir_EOR_32_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "EOR_32_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("XOR", ir::ident("operand1"), ir::ident("operand2"))));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_EOR_64_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "EOR_64_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("XOR", ir::ident("operand1"), ir::ident("operand2"))));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_EXTR_32_extract(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "EXTR_32_extract";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("!=", ir::ident("N"), ir::ident("sf")), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("m", "integer", ir::func_call("UInt", {}, {ir::ident("Rm")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("lsb", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("X", {}, {ir::ident("m")})));
        stmts.push_back(ir::let_decl("concat", "bits(BinOp(op='*', left=IntLiteral(value=2), right=Identifier(name='datasize')))", ir::bit_concat({ir::ident("operand1"), ir::ident("operand2")})));
        stmts.push_back(ir::assign(ir::ident("result"), ir::bit_slice(ir::ident("concat"), ir::bin_op("-", ir::bin_op("+", ir::ident("lsb"), ir::ident("datasize")), ir::int_lit(1)), ir::ident("lsb"), false)));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
    }

    return tree;
}

Tree build_ir_EXTR_64_extract(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "EXTR_64_extract";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("!=", ir::ident("N"), ir::ident("sf")), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("m", "integer", ir::func_call("UInt", {}, {ir::ident("Rm")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("lsb", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("X", {}, {ir::ident("m")})));
        stmts.push_back(ir::let_decl("concat", "bits(BinOp(op='*', left=IntLiteral(value=2), right=Identifier(name='datasize')))", ir::bit_concat({ir::ident("operand1"), ir::ident("operand2")})));
        stmts.push_back(ir::assign(ir::ident("result"), ir::bit_slice(ir::ident("concat"), ir::bin_op("-", ir::bin_op("+", ir::ident("lsb"), ir::ident("datasize")), ir::int_lit(1)), ir::ident("lsb"), false)));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
    }

    return tree;
}

Tree build_ir_LSL_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "LSL_UBFM_32M_bitfield";


    return tree;
}

Tree build_ir_LSL_UBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "LSL_UBFM_64M_bitfield";


    return tree;
}

Tree build_ir_LSR_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "LSR_UBFM_32M_bitfield";


    return tree;
}

Tree build_ir_LSR_UBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "LSR_UBFM_64M_bitfield";


    return tree;
}

Tree build_ir_MOV_ADD_32_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_ADD_32_addsub_imm";


    return tree;
}

Tree build_ir_MOV_ADD_64_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_ADD_64_addsub_imm";


    return tree;
}

Tree build_ir_MOV_MOVN_32_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_MOVN_32_movewide";


    return tree;
}

Tree build_ir_MOV_MOVN_64_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_MOVN_64_movewide";


    return tree;
}

Tree build_ir_MOV_MOVZ_32_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_MOVZ_32_movewide";


    return tree;
}

Tree build_ir_MOV_MOVZ_64_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_MOVZ_64_movewide";


    return tree;
}

Tree build_ir_MOV_ORR_32_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_ORR_32_log_imm";


    return tree;
}

Tree build_ir_MOV_ORR_64_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOV_ORR_64_log_imm";


    return tree;
}

Tree build_ir_MOVK_32_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOVK_32_movewide";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("hw"), ir::int_lit(1), ir::int_lit(1), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(16)", ir::ident("imm16")));
        stmts.push_back(ir::let_decl("pos", "integer", ir::bin_op("<<", ir::func_call("UInt", {}, {ir::ident("hw")}), ir::int_lit(4))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", ir::func_call("X", {}, {ir::ident("d")})));
        stmts.push_back(ir::assign(ir::bit_slice(ir::ident("result"), ir::bin_op("+", ir::ident("pos"), ir::int_lit(15)), ir::ident("pos"), false), ir::ident("imm")));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
    }

    return tree;
}

Tree build_ir_MOVK_64_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOVK_64_movewide";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("hw"), ir::int_lit(1), ir::int_lit(1), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(16)", ir::ident("imm16")));
        stmts.push_back(ir::let_decl("pos", "integer", ir::bin_op("<<", ir::func_call("UInt", {}, {ir::ident("hw")}), ir::int_lit(4))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", ir::func_call("X", {}, {ir::ident("d")})));
        stmts.push_back(ir::assign(ir::bit_slice(ir::ident("result"), ir::bin_op("+", ir::ident("pos"), ir::int_lit(15)), ir::ident("pos"), false), ir::ident("imm")));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
    }

    return tree;
}

Tree build_ir_MOVN_32_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOVN_32_movewide";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("hw"), ir::int_lit(1), ir::int_lit(1), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(16)", ir::ident("imm16")));
        stmts.push_back(ir::let_decl("pos", "integer", ir::bin_op("<<", ir::func_call("UInt", {}, {ir::ident("hw")}), ir::int_lit(4))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", ir::func_call("Zeros", {}, {})));
        stmts.push_back(ir::assign(ir::bit_slice(ir::ident("result"), ir::bin_op("+", ir::ident("pos"), ir::int_lit(15)), ir::ident("pos"), false), ir::ident("imm")));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::unary_op("NOT", ir::ident("result"))));
    }

    return tree;
}

Tree build_ir_MOVN_64_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOVN_64_movewide";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("hw"), ir::int_lit(1), ir::int_lit(1), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(16)", ir::ident("imm16")));
        stmts.push_back(ir::let_decl("pos", "integer", ir::bin_op("<<", ir::func_call("UInt", {}, {ir::ident("hw")}), ir::int_lit(4))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", ir::func_call("Zeros", {}, {})));
        stmts.push_back(ir::assign(ir::bit_slice(ir::ident("result"), ir::bin_op("+", ir::ident("pos"), ir::int_lit(15)), ir::ident("pos"), false), ir::ident("imm")));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::unary_op("NOT", ir::ident("result"))));
    }

    return tree;
}

Tree build_ir_MOVZ_32_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOVZ_32_movewide";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("hw"), ir::int_lit(1), ir::int_lit(1), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(16)", ir::ident("imm16")));
        stmts.push_back(ir::let_decl("pos", "integer", ir::bin_op("<<", ir::func_call("UInt", {}, {ir::ident("hw")}), ir::int_lit(4))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", ir::func_call("Zeros", {}, {})));
        stmts.push_back(ir::assign(ir::bit_slice(ir::ident("result"), ir::bin_op("+", ir::ident("pos"), ir::int_lit(15)), ir::ident("pos"), false), ir::ident("imm")));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
    }

    return tree;
}

Tree build_ir_MOVZ_64_movewide(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "MOVZ_64_movewide";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("==", ir::bit_slice(ir::ident("hw"), ir::int_lit(1), ir::int_lit(1), false), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(16)", ir::ident("imm16")));
        stmts.push_back(ir::let_decl("pos", "integer", ir::bin_op("<<", ir::func_call("UInt", {}, {ir::ident("hw")}), ir::int_lit(4))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::var_decl("result", "bits(datasize)", ir::func_call("Zeros", {}, {})));
        stmts.push_back(ir::assign(ir::bit_slice(ir::ident("result"), ir::bin_op("+", ir::ident("pos"), ir::int_lit(15)), ir::ident("pos"), false), ir::ident("imm")));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
    }

    return tree;
}

Tree build_ir_ORR_32_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ORR_32_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("OR", ir::ident("operand1"), ir::ident("operand2"))));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_ORR_64_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ORR_64_log_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::var_decl("imm", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"imm", "-"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(true)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::ident("imm")));
        stmts.push_back(ir::let_decl("result", "bits(datasize)", ir::bin_op("OR", ir::ident("operand1"), ir::ident("operand2"))));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_ROR_EXTR_32_extract(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ROR_EXTR_32_extract";


    return tree;
}

Tree build_ir_ROR_EXTR_64_extract(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "ROR_EXTR_64_extract";


    return tree;
}

Tree build_ir_SBFIZ_SBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SBFIZ_SBFM_32M_bitfield";


    return tree;
}

Tree build_ir_SBFIZ_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SBFIZ_SBFM_64M_bitfield";


    return tree;
}

Tree build_ir_SBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SBFM_32M_bitfield";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("1")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("||", ir::bin_op("||", ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0")), ir::bin_op("!=", ir::bit_slice(ir::ident("immr"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0"))), ir::bin_op("!=", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0")))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("s", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
        stmts.push_back(ir::let_decl("r", "integer", ir::func_call("UInt", {}, {ir::ident("immr")})));
        stmts.push_back(ir::var_decl("wmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("tmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"wmask", "tmask"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(false)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("src", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("bot", "bits(datasize)", ir::bin_op("AND", ir::func_call("ROR", {}, {ir::ident("src"), ir::ident("r")}), ir::ident("wmask"))));
        stmts.push_back(ir::let_decl("top", "bits(datasize)", ir::func_call("Replicate", {}, {ir::bit_slice(ir::ident("src"), ir::ident("s"), ir::ident("s"), false)})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bin_op("OR", ir::bin_op("AND", ir::ident("top"), ir::unary_op("NOT", ir::ident("tmask"))), ir::bin_op("AND", ir::ident("bot"), ir::ident("tmask")))));
    }

    return tree;
}

Tree build_ir_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SBFM_64M_bitfield";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("1")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("||", ir::bin_op("||", ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0")), ir::bin_op("!=", ir::bit_slice(ir::ident("immr"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0"))), ir::bin_op("!=", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0")))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("s", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
        stmts.push_back(ir::let_decl("r", "integer", ir::func_call("UInt", {}, {ir::ident("immr")})));
        stmts.push_back(ir::var_decl("wmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("tmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"wmask", "tmask"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(false)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("src", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("bot", "bits(datasize)", ir::bin_op("AND", ir::func_call("ROR", {}, {ir::ident("src"), ir::ident("r")}), ir::ident("wmask"))));
        stmts.push_back(ir::let_decl("top", "bits(datasize)", ir::func_call("Replicate", {}, {ir::bit_slice(ir::ident("src"), ir::ident("s"), ir::ident("s"), false)})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bin_op("OR", ir::bin_op("AND", ir::ident("top"), ir::unary_op("NOT", ir::ident("tmask"))), ir::bin_op("AND", ir::ident("bot"), ir::ident("tmask")))));
    }

    return tree;
}

Tree build_ir_SBFX_SBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SBFX_SBFM_32M_bitfield";


    return tree;
}

Tree build_ir_SBFX_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SBFX_SBFM_64M_bitfield";


    return tree;
}

Tree build_ir_SMAX_32_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SMAX_32_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("SInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Max", {}, {ir::func_call("SInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_SMAX_64_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SMAX_64_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("SInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Max", {}, {ir::func_call("SInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_SMIN_32_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SMIN_32_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("SInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Min", {}, {ir::func_call("SInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_SMIN_64_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SMIN_64_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("SInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Min", {}, {ir::func_call("SInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_SUB_32_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SUB_32_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "-"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::unary_op("NOT", ir::ident("operand2")), ir::bit_lit("1")})));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_SUB_64_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SUB_64_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "-"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::unary_op("NOT", ir::ident("operand2")), ir::bit_lit("1")})));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("result")})));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_SUBG_64_addsub_immtags(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SUBG_64_addsub_immtags";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_MTE")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("tag_offset", "bits(4)", ir::ident("imm4")));
        stmts.push_back(ir::let_decl("offset", "bits(64)", ir::func_call("LSL", {}, {ir::func_call("ZeroExtend", {ir::int_lit(64)}, {ir::ident("imm6")}), ir::ident("LOG2_TAG_GRANULE")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(64)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::int_lit(64)}, {}), ir::func_call("X", {ir::int_lit(64)}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("start_tag", "bits(4)", ir::func_call("AArch64_AllocationTagFromAddress", {}, {ir::ident("operand1")})));
        stmts.push_back(ir::let_decl("exclude", "bits(16)", ir::field_access(ir::func_call("GCR_EL1", {}, {}), "Exclude")));
        stmts.push_back(ir::let_decl("rtag", "bits(4)", ir::func_call("AArch64_ChooseNonExcludedTagOrZero", {}, {ir::ident("start_tag"), ir::ident("tag_offset"), ir::ident("exclude")})));
        stmts.push_back(ir::var_decl("result", "bits(64)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "-"}, ir::func_call("AddWithCarry", {ir::int_lit(64)}, {ir::ident("operand1"), ir::unary_op("NOT", ir::ident("offset")), ir::bit_lit("1")})));
        stmts.push_back(ir::assign(ir::ident("result"), ir::func_call("AArch64_AddressWithAllocationTag", {}, {ir::ident("result"), ir::ident("rtag")})));
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("SP", {ir::int_lit(64)}, {}), ir::ident("result")));
                branches.push_back({ ir::bin_op("==", ir::ident("d"), ir::int_lit(31)), std::move(stmts) });
            }
            {
                std::vector<ir::StmtPtr> stmts;
                stmts.push_back(ir::assign(ir::func_call("X", {ir::int_lit(64)}, {ir::ident("d")}), ir::ident("result")));
                branches.push_back({ nullptr, std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
    }

    return tree;
}

Tree build_ir_SUBS_32S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SUBS_32S_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("nzcv", "bits(4)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "nzcv"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::unary_op("NOT", ir::ident("operand2")), ir::bit_lit("1")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
        stmts.push_back(ir::assign(ir::field_access_multi(ir::ident("PSTATE"), {"N", "Z", "C", "V"}), ir::ident("nzcv")));
    }

    return tree;
}

Tree build_ir_SUBS_64S_addsub_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SUBS_64S_addsub_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "bits(24)", ir::if_expr(ir::bin_op("==", ir::ident("sh"), ir::bit_lit("0")), ir::bit_concat({ir::func_call("Zeros", {ir::int_lit(12)}, {}), ir::ident("imm12")}), ir::bit_concat({ir::ident("imm12"), ir::func_call("Zeros", {ir::int_lit(12)}, {})}))));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::if_expr(ir::bin_op("==", ir::ident("n"), ir::int_lit(31)), ir::func_call("SP", {ir::ident("datasize")}, {}), ir::func_call("X", {ir::ident("datasize")}, {ir::ident("n")}))));
        stmts.push_back(ir::let_decl("operand2", "bits(datasize)", ir::func_call("ZeroExtend", {}, {ir::ident("imm")})));
        stmts.push_back(ir::var_decl("result", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("nzcv", "bits(4)", nullptr));
        stmts.push_back(ir::tuple_assign({"result", "nzcv"}, ir::func_call("AddWithCarry", {ir::ident("datasize")}, {ir::ident("operand1"), ir::unary_op("NOT", ir::ident("operand2")), ir::bit_lit("1")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::ident("result")));
        stmts.push_back(ir::assign(ir::field_access_multi(ir::ident("PSTATE"), {"N", "Z", "C", "V"}), ir::ident("nzcv")));
    }

    return tree;
}

Tree build_ir_SXTB_SBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SXTB_SBFM_32M_bitfield";


    return tree;
}

Tree build_ir_SXTB_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SXTB_SBFM_64M_bitfield";


    return tree;
}

Tree build_ir_SXTH_SBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SXTH_SBFM_32M_bitfield";


    return tree;
}

Tree build_ir_SXTH_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SXTH_SBFM_64M_bitfield";


    return tree;
}

Tree build_ir_SXTW_SBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "SXTW_SBFM_64M_bitfield";


    return tree;
}

Tree build_ir_TST_ANDS_32S_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "TST_ANDS_32S_log_imm";


    return tree;
}

Tree build_ir_TST_ANDS_64S_log_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "TST_ANDS_64S_log_imm";


    return tree;
}

Tree build_ir_UBFIZ_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UBFIZ_UBFM_32M_bitfield";


    return tree;
}

Tree build_ir_UBFIZ_UBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UBFIZ_UBFM_64M_bitfield";


    return tree;
}

Tree build_ir_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UBFM_32M_bitfield";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("1")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("||", ir::bin_op("||", ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0")), ir::bin_op("!=", ir::bit_slice(ir::ident("immr"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0"))), ir::bin_op("!=", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0")))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("s", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
        stmts.push_back(ir::let_decl("r", "integer", ir::func_call("UInt", {}, {ir::ident("immr")})));
        stmts.push_back(ir::var_decl("wmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("tmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"wmask", "tmask"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(false)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("src", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("bot", "bits(datasize)", ir::bin_op("AND", ir::func_call("ROR", {}, {ir::ident("src"), ir::ident("r")}), ir::ident("wmask"))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bin_op("AND", ir::ident("bot"), ir::ident("tmask"))));
    }

    return tree;
}

Tree build_ir_UBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UBFM_64M_bitfield";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("1")), ir::bin_op("!=", ir::ident("N"), ir::bit_lit("1"))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::bin_op("&&", ir::bin_op("==", ir::ident("sf"), ir::bit_lit("0")), ir::bin_op("||", ir::bin_op("||", ir::bin_op("!=", ir::ident("N"), ir::bit_lit("0")), ir::bin_op("!=", ir::bit_slice(ir::ident("immr"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0"))), ir::bin_op("!=", ir::bit_slice(ir::ident("imms"), ir::int_lit(5), ir::int_lit(5), false), ir::bit_lit("0")))), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("s", "integer", ir::func_call("UInt", {}, {ir::ident("imms")})));
        stmts.push_back(ir::let_decl("r", "integer", ir::func_call("UInt", {}, {ir::ident("immr")})));
        stmts.push_back(ir::var_decl("wmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::var_decl("tmask", "bits(datasize)", nullptr));
        stmts.push_back(ir::tuple_assign({"wmask", "tmask"}, ir::func_call("DecodeBitMasks", {ir::ident("datasize")}, {ir::ident("N"), ir::ident("imms"), ir::ident("immr"), ir::bool_lit(false)})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("src", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("bot", "bits(datasize)", ir::bin_op("AND", ir::func_call("ROR", {}, {ir::ident("src"), ir::ident("r")}), ir::ident("wmask"))));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bin_op("AND", ir::ident("bot"), ir::ident("tmask"))));
    }

    return tree;
}

Tree build_ir_UBFX_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UBFX_UBFM_32M_bitfield";


    return tree;
}

Tree build_ir_UBFX_UBFM_64M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UBFX_UBFM_64M_bitfield";


    return tree;
}

Tree build_ir_UMAX_32U_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UMAX_32U_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("UInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Max", {}, {ir::func_call("UInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_UMAX_64U_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UMAX_64U_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("UInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Max", {}, {ir::func_call("UInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_UMIN_32U_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UMIN_32U_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("UInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Min", {}, {ir::func_call("UInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_UMIN_64U_minmax_imm(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UMIN_64U_minmax_imm";


    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
        {
            std::vector<std::pair<ir::ExprPtr, std::vector<ir::StmtPtr>>> branches;
            {
                std::vector<ir::StmtPtr> stmts;
                branches.push_back({ ir::unary_op("!", ir::func_call("IsFeatureImplemented", {}, {ir::ident("FEAT_CSSC")})), std::move(stmts) });
            }
            stmts.push_back(ir::if_stmt(std::move(branches)));
        }
        stmts.push_back(ir::let_decl("d", "integer", ir::func_call("UInt", {}, {ir::ident("Rd")})));
        stmts.push_back(ir::let_decl("n", "integer", ir::func_call("UInt", {}, {ir::ident("Rn")})));
        stmts.push_back(ir::let_decl("datasize", "integer", ir::bin_op("<<", ir::int_lit(32), ir::func_call("UInt", {}, {ir::ident("sf")}))));
        stmts.push_back(ir::let_decl("imm", "integer", ir::func_call("UInt", {}, {ir::ident("imm8")})));
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
        stmts.push_back(ir::let_decl("operand1", "bits(datasize)", ir::func_call("X", {}, {ir::ident("n")})));
        stmts.push_back(ir::let_decl("result", "integer", ir::func_call("Min", {}, {ir::func_call("UInt", {}, {ir::ident("operand1")}), ir::ident("imm")})));
        stmts.push_back(ir::assign(ir::func_call("X", {ir::ident("datasize")}, {ir::ident("d")}), ir::bit_slice(ir::ident("result"), ir::bin_op("-", ir::ident("datasize"), ir::int_lit(1)), ir::int_lit(0), false)));
    }

    return tree;
}

Tree build_ir_UXTB_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UXTB_UBFM_32M_bitfield";


    return tree;
}

Tree build_ir_UXTH_UBFM_32M_bitfield(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UXTH_UBFM_32M_bitfield";


    return tree;
}

} // namespace ir
} // namespace veda64