// Auto-generated IR builder functions for reserved
// Do not edit - generated by parse_arm64_xml.py
#include "ir.hpp"

namespace veda64 {
namespace ir {

Tree build_ir_UDF_only_perm_undef(uint32_t insn) {
    Tree tree;
    tree.encoding_name = "UDF_only_perm_undef";

    tree.fields["imm16"] = (insn >> 0) & 0xFFFF;

    // Decode pseudocode
    {
        auto& stmts = tree.decode_stmts;
    }

    // Execute pseudocode
    {
        auto& stmts = tree.execute_stmts;
    }

    return tree;
}

} // namespace ir
} // namespace veda64