#pragma once

#include <cstdint>
#include <cstddef>
#include <string>
#include <vector>
#include <optional>
#include <memory>

namespace veda64 {

// Library version
constexpr int VERSION_MAJOR = 0;
constexpr int VERSION_MINOR = 1;
constexpr int VERSION_PATCH = 0;

// Byte-order conversion utilities
// ARM64 stores instructions in little-endian byte order
// These convert between raw memory bytes and the uint32_t used by decode()
// e.g., PACIBSP in memory: {0x7f, 0x23, 0x03, 0xd5} -> 0xd503237f

// Read a little-endian uint32_t from 4 bytes in memory
// {0x7f, 0x23, 0x03, 0xd5} -> 0xd503237f
inline uint32_t from_bytes(const uint8_t* bytes) {
    return static_cast<uint32_t>(bytes[0]) |
           (static_cast<uint32_t>(bytes[1]) << 8) |
           (static_cast<uint32_t>(bytes[2]) << 16) |
           (static_cast<uint32_t>(bytes[3]) << 24);
}

// Write a uint32_t as 4 little-endian bytes to memory
// 0xd503237f -> {0x7f, 0x23, 0x03, 0xd5}
inline void to_bytes(uint32_t insn, uint8_t* bytes) {
    bytes[0] = static_cast<uint8_t>(insn);
    bytes[1] = static_cast<uint8_t>(insn >> 8);
    bytes[2] = static_cast<uint8_t>(insn >> 16);
    bytes[3] = static_cast<uint8_t>(insn >> 24);
}

// ARM64 DecodeBitMasks - decodes N:imms:immr into a bitmask immediate
inline uint64_t decode_bit_masks(uint32_t N, uint32_t imms, uint32_t immr, bool is_64bit) {
    uint32_t len = 0;
    uint32_t combined = (N << 6) | (~imms & 0x3F);
    for (int i = 6; i >= 0; --i) {
        if (combined & (1u << i)) { len = i; break; }
    }
    uint32_t esize = 1u << len;
    uint32_t levels = esize - 1;
    uint32_t S = imms & levels;
    uint32_t R = immr & levels;
    uint64_t welem = (S + 1 == 64) ? ~0ULL : ((1ULL << (S + 1)) - 1);
    uint64_t emask = (esize == 64) ? ~0ULL : ((1ULL << esize) - 1);
    if (R != 0) {
        welem = ((welem >> R) | (welem << (esize - R))) & emask;
    }
    uint64_t result = 0;
    uint32_t regsize = is_64bit ? 64 : 32;
    for (uint32_t i = 0; i < regsize; i += esize) {
        result |= welem << i;
    }
    if (!is_64bit) result &= 0xFFFFFFFFULL;
    return result;
}

// Mnemonic enumeration
enum class Mnemonic {
    ABS,
    ADC,
    ADCLB,
    ADCLT,
    ADCS,
    ADD,
    ADDG,
    ADDHA,
    ADDHN,
    ADDHNB,
    ADDHNT,
    ADDP,
    ADDPL,
    ADDPT,
    ADDQP,
    ADDQV,
    ADDS,
    ADDSPL,
    ADDSUBP,
    ADDSVL,
    ADDV,
    ADDVA,
    ADDVL,
    ADR,
    ADRP,
    AESD,
    AESDIMC,
    AESE,
    AESEMC,
    AESIMC,
    AESMC,
    AND,
    ANDQV,
    ANDS,
    ANDV,
    ASR,
    ASRD,
    ASRR,
    ASRV,
    AUTDA,
    AUTDB,
    AUTDZA,
    AUTDZB,
    AUTIA,
    AUTIA1716,
    AUTIA171615,
    AUTIASP,
    AUTIASPPC,
    AUTIASPPCR,
    AUTIAZ,
    AUTIB,
    AUTIB1716,
    AUTIB171615,
    AUTIBSP,
    AUTIBSPPC,
    AUTIBSPPCR,
    AUTIBZ,
    AUTIZA,
    AUTIZB,
    AXFLAG,
    B,
    BC,
    BCAX,
    BDEP,
    BEXT,
    BF1CVT,
    BF1CVTL,
    BF1CVTLT,
    BF2CVT,
    BF2CVTL,
    BF2CVTLT,
    BFADD,
    BFCLAMP,
    BFCVT,
    BFCVTN,
    BFCVTNT,
    BFDOT,
    BFM,
    BFMAX,
    BFMAXNM,
    BFMIN,
    BFMINNM,
    BFMLA,
    BFMLAL,
    BFMLALB,
    BFMLALT,
    BFMLS,
    BFMLSL,
    BFMLSLB,
    BFMLSLT,
    BFMMLA,
    BFMOP4A,
    BFMOP4S,
    BFMOPA,
    BFMOPS,
    BFMUL,
    BFSCALE,
    BFSUB,
    BFTMOPA,
    BFVDOT,
    BGRP,
    BIC,
    BICS,
    BIF,
    BIT,
    BL,
    BLR,
    BLRAA,
    BLRAAZ,
    BLRAB,
    BLRABZ,
    BMOPA,
    BMOPS,
    BR,
    BRAA,
    BRAAZ,
    BRAB,
    BRABZ,
    BRK,
    BRKA,
    BRKAS,
    BRKB,
    BRKBS,
    BRKN,
    BRKNS,
    BRKPA,
    BRKPAS,
    BRKPB,
    BRKPBS,
    BSL,
    BSL1N,
    BSL2N,
    BTI,
    CADD,
    CAS,
    CASA,
    CASAB,
    CASAH,
    CASAL,
    CASALB,
    CASALH,
    CASALT,
    CASAT,
    CASB,
    CASH,
    CASL,
    CASLB,
    CASLH,
    CASLT,
    CASP,
    CASPA,
    CASPAL,
    CASPALT,
    CASPAT,
    CASPL,
    CASPLT,
    CASPT,
    CAST,
    CBBEQ,
    CBBGE,
    CBBGT,
    CBBHI,
    CBBHS,
    CBBNE,
    CBEQ,
    CBGE,
    CBGT,
    CBHEQ,
    CBHGE,
    CBHGT,
    CBHHI,
    CBHHS,
    CBHI,
    CBHNE,
    CBHS,
    CBLO,
    CBLT,
    CBNE,
    CBNZ,
    CBZ,
    CCMN,
    CCMP,
    CDOT,
    CFINV,
    CHKFEAT,
    CLASTA,
    CLASTB,
    CLRBHB,
    CLREX,
    CLS,
    CLZ,
    CMEQ,
    CMGE,
    CMGT,
    CMHI,
    CMHS,
    CMLA,
    CMLE,
    CMLT,
    CMPEQ,
    CMPGE,
    CMPGT,
    CMPHI,
    CMPHS,
    CMPLE,
    CMPLO,
    CMPLS,
    CMPLT,
    CMPNE,
    CMTST,
    CNOT,
    CNT,
    CNTB,
    CNTD,
    CNTH,
    CNTP,
    CNTW,
    COMPACT,
    CPY,
    CPYE,
    CPYEN,
    CPYERN,
    CPYERT,
    CPYERTN,
    CPYERTRN,
    CPYERTWN,
    CPYET,
    CPYETN,
    CPYETRN,
    CPYETWN,
    CPYEWN,
    CPYEWT,
    CPYEWTN,
    CPYEWTRN,
    CPYEWTWN,
    CPYFE,
    CPYFEN,
    CPYFERN,
    CPYFERT,
    CPYFERTN,
    CPYFERTRN,
    CPYFERTWN,
    CPYFET,
    CPYFETN,
    CPYFETRN,
    CPYFETWN,
    CPYFEWN,
    CPYFEWT,
    CPYFEWTN,
    CPYFEWTRN,
    CPYFEWTWN,
    CPYFM,
    CPYFMN,
    CPYFMRN,
    CPYFMRT,
    CPYFMRTN,
    CPYFMRTRN,
    CPYFMRTWN,
    CPYFMT,
    CPYFMTN,
    CPYFMTRN,
    CPYFMTWN,
    CPYFMWN,
    CPYFMWT,
    CPYFMWTN,
    CPYFMWTRN,
    CPYFMWTWN,
    CPYFP,
    CPYFPN,
    CPYFPRN,
    CPYFPRT,
    CPYFPRTN,
    CPYFPRTRN,
    CPYFPRTWN,
    CPYFPT,
    CPYFPTN,
    CPYFPTRN,
    CPYFPTWN,
    CPYFPWN,
    CPYFPWT,
    CPYFPWTN,
    CPYFPWTRN,
    CPYFPWTWN,
    CPYM,
    CPYMN,
    CPYMRN,
    CPYMRT,
    CPYMRTN,
    CPYMRTRN,
    CPYMRTWN,
    CPYMT,
    CPYMTN,
    CPYMTRN,
    CPYMTWN,
    CPYMWN,
    CPYMWT,
    CPYMWTN,
    CPYMWTRN,
    CPYMWTWN,
    CPYP,
    CPYPN,
    CPYPRN,
    CPYPRT,
    CPYPRTN,
    CPYPRTRN,
    CPYPRTWN,
    CPYPT,
    CPYPTN,
    CPYPTRN,
    CPYPTWN,
    CPYPWN,
    CPYPWT,
    CPYPWTN,
    CPYPWTRN,
    CPYPWTWN,
    CRC32B,
    CRC32CB,
    CRC32CH,
    CRC32CW,
    CRC32CX,
    CRC32H,
    CRC32W,
    CRC32X,
    CSDB,
    CSEL,
    CSINC,
    CSINV,
    CSNEG,
    CTERMEQ,
    CTERMNE,
    CTZ,
    DCPS1,
    DCPS2,
    DCPS3,
    DECB,
    DECD,
    DECH,
    DECP,
    DECW,
    DGH,
    DMB,
    DRPS,
    DSB,
    DUP,
    DUPM,
    DUPQ,
    EON,
    EOR,
    EOR3,
    EORBT,
    EORQV,
    EORS,
    EORTB,
    EORV,
    ERET,
    ERETAA,
    ERETAB,
    ESB,
    EXPAND,
    EXT,
    EXTQ,
    EXTR,
    F1CVT,
    F1CVTL,
    F1CVTLT,
    F2CVT,
    F2CVTL,
    F2CVTLT,
    FABD,
    FABS,
    FACGE,
    FACGT,
    FADD,
    FADDA,
    FADDP,
    FADDQV,
    FADDV,
    FAMAX,
    FAMIN,
    FCADD,
    FCCMP,
    FCCMPE,
    FCLAMP,
    FCMEQ,
    FCMGE,
    FCMGT,
    FCMLA,
    FCMLE,
    FCMLT,
    FCMNE,
    FCMP,
    FCMPE,
    FCMUO,
    FCPY,
    FCSEL,
    FCVT,
    FCVTAS,
    FCVTAU,
    FCVTL,
    FCVTLT,
    FCVTMS,
    FCVTMU,
    FCVTN,
    FCVTNB,
    FCVTNS,
    FCVTNT,
    FCVTNU,
    FCVTPS,
    FCVTPU,
    FCVTX,
    FCVTXN,
    FCVTXNT,
    FCVTZS,
    FCVTZSN,
    FCVTZU,
    FCVTZUN,
    FDIV,
    FDIVR,
    FDOT,
    FDUP,
    FEXPA,
    FIRSTP,
    FJCVTZS,
    FLOGB,
    FMAD,
    FMADD,
    FMAX,
    FMAXNM,
    FMAXNMP,
    FMAXNMQV,
    FMAXNMV,
    FMAXP,
    FMAXQV,
    FMAXV,
    FMIN,
    FMINNM,
    FMINNMP,
    FMINNMQV,
    FMINNMV,
    FMINP,
    FMINQV,
    FMINV,
    FMLA,
    FMLAL,
    FMLAL2,
    FMLALB,
    FMLALL,
    FMLALLBB,
    FMLALLBT,
    FMLALLTB,
    FMLALLTT,
    FMLALT,
    FMLS,
    FMLSL,
    FMLSL2,
    FMLSLB,
    FMLSLT,
    FMMLA,
    FMOP4A,
    FMOP4S,
    FMOPA,
    FMOPS,
    FMOV,
    FMSB,
    FMSUB,
    FMUL,
    FMULX,
    FNEG,
    FNMAD,
    FNMADD,
    FNMLA,
    FNMLS,
    FNMSB,
    FNMSUB,
    FNMUL,
    FRECPE,
    FRECPS,
    FRECPX,
    FRINT32X,
    FRINT32Z,
    FRINT64X,
    FRINT64Z,
    FRINTA,
    FRINTI,
    FRINTM,
    FRINTN,
    FRINTP,
    FRINTX,
    FRINTZ,
    FRSQRTE,
    FRSQRTS,
    FSCALE,
    FSQRT,
    FSUB,
    FSUBR,
    FTMAD,
    FTMOPA,
    FTSMUL,
    FTSSEL,
    FVDOT,
    FVDOTB,
    FVDOTT,
    GCSB,
    GCSSTR,
    GCSSTTR,
    GMI,
    HINT,
    HISTCNT,
    HISTSEG,
    HLT,
    HVC,
    INCB,
    INCD,
    INCH,
    INCP,
    INCW,
    INDEX,
    INS,
    INSR,
    IRG,
    ISB,
    LASTA,
    LASTB,
    LASTP,
    LD1,
    LD1B,
    LD1D,
    LD1H,
    LD1Q,
    LD1R,
    LD1RB,
    LD1RD,
    LD1RH,
    LD1ROB,
    LD1ROD,
    LD1ROH,
    LD1ROW,
    LD1RQB,
    LD1RQD,
    LD1RQH,
    LD1RQW,
    LD1RSB,
    LD1RSH,
    LD1RSW,
    LD1RW,
    LD1SB,
    LD1SH,
    LD1SW,
    LD1W,
    LD2,
    LD2B,
    LD2D,
    LD2H,
    LD2Q,
    LD2R,
    LD2W,
    LD3,
    LD3B,
    LD3D,
    LD3H,
    LD3Q,
    LD3R,
    LD3W,
    LD4,
    LD4B,
    LD4D,
    LD4H,
    LD4Q,
    LD4R,
    LD4W,
    LD64B,
    LDADD,
    LDADDA,
    LDADDAB,
    LDADDAH,
    LDADDAL,
    LDADDALB,
    LDADDALH,
    LDADDB,
    LDADDH,
    LDADDL,
    LDADDLB,
    LDADDLH,
    LDAP,
    LDAP1,
    LDAPP,
    LDAPR,
    LDAPRB,
    LDAPRH,
    LDAPUR,
    LDAPURB,
    LDAPURH,
    LDAPURSB,
    LDAPURSH,
    LDAPURSW,
    LDAR,
    LDARB,
    LDARH,
    LDATXR,
    LDAXP,
    LDAXR,
    LDAXRB,
    LDAXRH,
    LDBFADD,
    LDBFADDA,
    LDBFADDAL,
    LDBFADDL,
    LDBFMAX,
    LDBFMAXA,
    LDBFMAXAL,
    LDBFMAXL,
    LDBFMAXNM,
    LDBFMAXNMA,
    LDBFMAXNMAL,
    LDBFMAXNML,
    LDBFMIN,
    LDBFMINA,
    LDBFMINAL,
    LDBFMINL,
    LDBFMINNM,
    LDBFMINNMA,
    LDBFMINNMAL,
    LDBFMINNML,
    LDCLR,
    LDCLRA,
    LDCLRAB,
    LDCLRAH,
    LDCLRAL,
    LDCLRALB,
    LDCLRALH,
    LDCLRB,
    LDCLRH,
    LDCLRL,
    LDCLRLB,
    LDCLRLH,
    LDCLRP,
    LDCLRPA,
    LDCLRPAL,
    LDCLRPL,
    LDEOR,
    LDEORA,
    LDEORAB,
    LDEORAH,
    LDEORAL,
    LDEORALB,
    LDEORALH,
    LDEORB,
    LDEORH,
    LDEORL,
    LDEORLB,
    LDEORLH,
    LDFADD,
    LDFADDA,
    LDFADDAL,
    LDFADDL,
    LDFF1B,
    LDFF1D,
    LDFF1H,
    LDFF1SB,
    LDFF1SH,
    LDFF1SW,
    LDFF1W,
    LDFMAX,
    LDFMAXA,
    LDFMAXAL,
    LDFMAXL,
    LDFMAXNM,
    LDFMAXNMA,
    LDFMAXNMAL,
    LDFMAXNML,
    LDFMIN,
    LDFMINA,
    LDFMINAL,
    LDFMINL,
    LDFMINNM,
    LDFMINNMA,
    LDFMINNMAL,
    LDFMINNML,
    LDG,
    LDGM,
    LDIAPP,
    LDLAR,
    LDLARB,
    LDLARH,
    LDNF1B,
    LDNF1D,
    LDNF1H,
    LDNF1SB,
    LDNF1SH,
    LDNF1SW,
    LDNF1W,
    LDNP,
    LDNT1B,
    LDNT1D,
    LDNT1H,
    LDNT1SB,
    LDNT1SH,
    LDNT1SW,
    LDNT1W,
    LDP,
    LDPSW,
    LDR,
    LDRAA,
    LDRAB,
    LDRB,
    LDRH,
    LDRSB,
    LDRSH,
    LDRSW,
    LDSET,
    LDSETA,
    LDSETAB,
    LDSETAH,
    LDSETAL,
    LDSETALB,
    LDSETALH,
    LDSETB,
    LDSETH,
    LDSETL,
    LDSETLB,
    LDSETLH,
    LDSETP,
    LDSETPA,
    LDSETPAL,
    LDSETPL,
    LDSMAX,
    LDSMAXA,
    LDSMAXAB,
    LDSMAXAH,
    LDSMAXAL,
    LDSMAXALB,
    LDSMAXALH,
    LDSMAXB,
    LDSMAXH,
    LDSMAXL,
    LDSMAXLB,
    LDSMAXLH,
    LDSMIN,
    LDSMINA,
    LDSMINAB,
    LDSMINAH,
    LDSMINAL,
    LDSMINALB,
    LDSMINALH,
    LDSMINB,
    LDSMINH,
    LDSMINL,
    LDSMINLB,
    LDSMINLH,
    LDTADD,
    LDTADDA,
    LDTADDAL,
    LDTADDL,
    LDTCLR,
    LDTCLRA,
    LDTCLRAL,
    LDTCLRL,
    LDTNP,
    LDTP,
    LDTR,
    LDTRB,
    LDTRH,
    LDTRSB,
    LDTRSH,
    LDTRSW,
    LDTSET,
    LDTSETA,
    LDTSETAL,
    LDTSETL,
    LDTXR,
    LDUMAX,
    LDUMAXA,
    LDUMAXAB,
    LDUMAXAH,
    LDUMAXAL,
    LDUMAXALB,
    LDUMAXALH,
    LDUMAXB,
    LDUMAXH,
    LDUMAXL,
    LDUMAXLB,
    LDUMAXLH,
    LDUMIN,
    LDUMINA,
    LDUMINAB,
    LDUMINAH,
    LDUMINAL,
    LDUMINALB,
    LDUMINALH,
    LDUMINB,
    LDUMINH,
    LDUMINL,
    LDUMINLB,
    LDUMINLH,
    LDUR,
    LDURB,
    LDURH,
    LDURSB,
    LDURSH,
    LDURSW,
    LDXP,
    LDXR,
    LDXRB,
    LDXRH,
    LSL,
    LSLR,
    LSLV,
    LSR,
    LSRR,
    LSRV,
    LUTI2,
    LUTI4,
    LUTI6,
    MAD,
    MADD,
    MADDPT,
    MADPT,
    MATCH,
    MLA,
    MLAPT,
    MLS,
    MOVA,
    MOVAZ,
    MOVI,
    MOVK,
    MOVN,
    MOVPRFX,
    MOVT,
    MOVZ,
    MRRS,
    MRS,
    MSB,
    MSR,
    MSRR,
    MSUB,
    MSUBPT,
    MUL,
    MVNI,
    NAND,
    NANDS,
    NBSL,
    NEG,
    NMATCH,
    NOP,
    NOR,
    NORS,
    NOT,
    ORN,
    ORNS,
    ORQV,
    ORR,
    ORRS,
    ORV,
    PACDA,
    PACDB,
    PACDZA,
    PACDZB,
    PACGA,
    PACIA,
    PACIA1716,
    PACIA171615,
    PACIASP,
    PACIASPPC,
    PACIAZ,
    PACIB,
    PACIB1716,
    PACIB171615,
    PACIBSP,
    PACIBSPPC,
    PACIBZ,
    PACIZA,
    PACIZB,
    PACM,
    PACNBIASPPC,
    PACNBIBSPPC,
    PEXT,
    PFALSE,
    PFIRST,
    PMLAL,
    PMOV,
    PMUL,
    PMULL,
    PMULLB,
    PMULLT,
    PNEXT,
    PRFB,
    PRFD,
    PRFH,
    PRFM,
    PRFUM,
    PRFW,
    PSB,
    PSEL,
    PTEST,
    PTRUE,
    PTRUES,
    PUNPKHI,
    PUNPKLO,
    RADDHN,
    RADDHNB,
    RADDHNT,
    RAX1,
    RBIT,
    RCWCAS,
    RCWCASA,
    RCWCASAL,
    RCWCASL,
    RCWCASP,
    RCWCASPA,
    RCWCASPAL,
    RCWCASPL,
    RCWCLR,
    RCWCLRA,
    RCWCLRAL,
    RCWCLRL,
    RCWCLRP,
    RCWCLRPA,
    RCWCLRPAL,
    RCWCLRPL,
    RCWSCAS,
    RCWSCASA,
    RCWSCASAL,
    RCWSCASL,
    RCWSCASP,
    RCWSCASPA,
    RCWSCASPAL,
    RCWSCASPL,
    RCWSCLR,
    RCWSCLRA,
    RCWSCLRAL,
    RCWSCLRL,
    RCWSCLRP,
    RCWSCLRPA,
    RCWSCLRPAL,
    RCWSCLRPL,
    RCWSET,
    RCWSETA,
    RCWSETAL,
    RCWSETL,
    RCWSETP,
    RCWSETPA,
    RCWSETPAL,
    RCWSETPL,
    RCWSSET,
    RCWSSETA,
    RCWSSETAL,
    RCWSSETL,
    RCWSSETP,
    RCWSSETPA,
    RCWSSETPAL,
    RCWSSETPL,
    RCWSSWP,
    RCWSSWPA,
    RCWSSWPAL,
    RCWSSWPL,
    RCWSSWPP,
    RCWSSWPPA,
    RCWSSWPPAL,
    RCWSSWPPL,
    RCWSWP,
    RCWSWPA,
    RCWSWPAL,
    RCWSWPL,
    RCWSWPP,
    RCWSWPPA,
    RCWSWPPAL,
    RCWSWPPL,
    RDFFR,
    RDFFRS,
    RDSVL,
    RDVL,
    RET,
    RETAA,
    RETAASPPC,
    RETAASPPCR,
    RETAB,
    RETABSPPC,
    RETABSPPCR,
    REV,
    REV16,
    REV32,
    REV64,
    REVB,
    REVD,
    REVH,
    REVW,
    RMIF,
    RORV,
    RPRFM,
    RSHRN,
    RSHRNB,
    RSHRNT,
    RSUBHN,
    RSUBHNB,
    RSUBHNT,
    SABA,
    SABAL,
    SABALB,
    SABALT,
    SABD,
    SABDL,
    SABDLB,
    SABDLT,
    SADALP,
    SADDL,
    SADDLB,
    SADDLBT,
    SADDLP,
    SADDLT,
    SADDLV,
    SADDV,
    SADDW,
    SADDWB,
    SADDWT,
    SB,
    SBC,
    SBCLB,
    SBCLT,
    SBCS,
    SBFM,
    SCLAMP,
    SCVTF,
    SCVTFLT,
    SDIV,
    SDIVR,
    SDOT,
    SEL,
    SETE,
    SETEN,
    SETET,
    SETETN,
    SETF16,
    SETF8,
    SETFFR,
    SETGE,
    SETGEN,
    SETGET,
    SETGETN,
    SETGM,
    SETGMN,
    SETGMT,
    SETGMTN,
    SETGP,
    SETGPN,
    SETGPT,
    SETGPTN,
    SETM,
    SETMN,
    SETMT,
    SETMTN,
    SETP,
    SETPN,
    SETPT,
    SETPTN,
    SEV,
    SEVL,
    SHA1C,
    SHA1H,
    SHA1M,
    SHA1P,
    SHA1SU0,
    SHA1SU1,
    SHA256H,
    SHA256H2,
    SHA256SU0,
    SHA256SU1,
    SHA512H,
    SHA512H2,
    SHA512SU0,
    SHA512SU1,
    SHADD,
    SHL,
    SHLL,
    SHRN,
    SHRNB,
    SHRNT,
    SHSUB,
    SHSUBR,
    SHUH,
    SLI,
    SM3PARTW1,
    SM3PARTW2,
    SM3SS1,
    SM3TT1A,
    SM3TT1B,
    SM3TT2A,
    SM3TT2B,
    SM4E,
    SM4EKEY,
    SMADDL,
    SMAX,
    SMAXP,
    SMAXQV,
    SMAXV,
    SMC,
    SMIN,
    SMINP,
    SMINQV,
    SMINV,
    SMLAL,
    SMLALB,
    SMLALL,
    SMLALT,
    SMLSL,
    SMLSLB,
    SMLSLL,
    SMLSLT,
    SMMLA,
    SMOP4A,
    SMOP4S,
    SMOPA,
    SMOPS,
    SMOV,
    SMSUBL,
    SMULH,
    SMULL,
    SMULLB,
    SMULLT,
    SPLICE,
    SQABS,
    SQADD,
    SQCADD,
    SQCVT,
    SQCVTN,
    SQCVTU,
    SQCVTUN,
    SQDECB,
    SQDECD,
    SQDECH,
    SQDECP,
    SQDECW,
    SQDMLAL,
    SQDMLALB,
    SQDMLALBT,
    SQDMLALT,
    SQDMLSL,
    SQDMLSLB,
    SQDMLSLBT,
    SQDMLSLT,
    SQDMULH,
    SQDMULL,
    SQDMULLB,
    SQDMULLT,
    SQINCB,
    SQINCD,
    SQINCH,
    SQINCP,
    SQINCW,
    SQNEG,
    SQRDCMLAH,
    SQRDMLAH,
    SQRDMLSH,
    SQRDMULH,
    SQRSHL,
    SQRSHLR,
    SQRSHR,
    SQRSHRN,
    SQRSHRNB,
    SQRSHRNT,
    SQRSHRU,
    SQRSHRUN,
    SQRSHRUNB,
    SQRSHRUNT,
    SQSHL,
    SQSHLR,
    SQSHLU,
    SQSHRN,
    SQSHRNB,
    SQSHRNT,
    SQSHRUN,
    SQSHRUNB,
    SQSHRUNT,
    SQSUB,
    SQSUBR,
    SQXTN,
    SQXTNB,
    SQXTNT,
    SQXTUN,
    SQXTUNB,
    SQXTUNT,
    SRHADD,
    SRI,
    SRSHL,
    SRSHLR,
    SRSHR,
    SRSRA,
    SSHL,
    SSHLL,
    SSHLLB,
    SSHLLT,
    SSHR,
    SSRA,
    SSUBL,
    SSUBLB,
    SSUBLBT,
    SSUBLT,
    SSUBLTB,
    SSUBW,
    SSUBWB,
    SSUBWT,
    ST1,
    ST1B,
    ST1D,
    ST1H,
    ST1Q,
    ST1W,
    ST2,
    ST2B,
    ST2D,
    ST2G,
    ST2H,
    ST2Q,
    ST2W,
    ST3,
    ST3B,
    ST3D,
    ST3H,
    ST3Q,
    ST3W,
    ST4,
    ST4B,
    ST4D,
    ST4H,
    ST4Q,
    ST4W,
    ST64B,
    ST64BV,
    ST64BV0,
    STBFADD,
    STBFADDL,
    STBFMAX,
    STBFMAXL,
    STBFMAXNM,
    STBFMAXNML,
    STBFMIN,
    STBFMINL,
    STBFMINNM,
    STBFMINNML,
    STCPH,
    STFADD,
    STFADDL,
    STFMAX,
    STFMAXL,
    STFMAXNM,
    STFMAXNML,
    STFMIN,
    STFMINL,
    STFMINNM,
    STFMINNML,
    STG,
    STGM,
    STGP,
    STILP,
    STL1,
    STLLR,
    STLLRB,
    STLLRH,
    STLP,
    STLR,
    STLRB,
    STLRH,
    STLTXR,
    STLUR,
    STLURB,
    STLURH,
    STLXP,
    STLXR,
    STLXRB,
    STLXRH,
    STMOPA,
    STNP,
    STNT1B,
    STNT1D,
    STNT1H,
    STNT1W,
    STP,
    STR,
    STRB,
    STRH,
    STSHH,
    STTNP,
    STTP,
    STTR,
    STTRB,
    STTRH,
    STTXR,
    STUR,
    STURB,
    STURH,
    STXP,
    STXR,
    STXRB,
    STXRH,
    STZ2G,
    STZG,
    STZGM,
    SUB,
    SUBG,
    SUBHN,
    SUBHNB,
    SUBHNT,
    SUBP,
    SUBPS,
    SUBPT,
    SUBR,
    SUBS,
    SUDOT,
    SUMLALL,
    SUMOP4A,
    SUMOP4S,
    SUMOPA,
    SUMOPS,
    SUNPK,
    SUNPKHI,
    SUNPKLO,
    SUQADD,
    SUTMOPA,
    SUVDOT,
    SVC,
    SVDOT,
    SWP,
    SWPA,
    SWPAB,
    SWPAH,
    SWPAL,
    SWPALB,
    SWPALH,
    SWPB,
    SWPH,
    SWPL,
    SWPLB,
    SWPLH,
    SWPP,
    SWPPA,
    SWPPAL,
    SWPPL,
    SWPT,
    SWPTA,
    SWPTAL,
    SWPTL,
    SXTB,
    SXTH,
    SXTW,
    SYS,
    SYSL,
    SYSP,
    TBL,
    TBLQ,
    TBNZ,
    TBX,
    TBXQ,
    TBZ,
    TRN1,
    TRN2,
    TSB,
    UABA,
    UABAL,
    UABALB,
    UABALT,
    UABD,
    UABDL,
    UABDLB,
    UABDLT,
    UADALP,
    UADDL,
    UADDLB,
    UADDLP,
    UADDLT,
    UADDLV,
    UADDV,
    UADDW,
    UADDWB,
    UADDWT,
    UBFM,
    UCLAMP,
    UCVTF,
    UCVTFLT,
    UDF,
    UDIV,
    UDIVR,
    UDOT,
    UHADD,
    UHSUB,
    UHSUBR,
    UMADDL,
    UMAX,
    UMAXP,
    UMAXQV,
    UMAXV,
    UMIN,
    UMINP,
    UMINQV,
    UMINV,
    UMLAL,
    UMLALB,
    UMLALL,
    UMLALT,
    UMLSL,
    UMLSLB,
    UMLSLL,
    UMLSLT,
    UMMLA,
    UMOP4A,
    UMOP4S,
    UMOPA,
    UMOPS,
    UMOV,
    UMSUBL,
    UMULH,
    UMULL,
    UMULLB,
    UMULLT,
    UQADD,
    UQCVT,
    UQCVTN,
    UQDECB,
    UQDECD,
    UQDECH,
    UQDECP,
    UQDECW,
    UQINCB,
    UQINCD,
    UQINCH,
    UQINCP,
    UQINCW,
    UQRSHL,
    UQRSHLR,
    UQRSHR,
    UQRSHRN,
    UQRSHRNB,
    UQRSHRNT,
    UQSHL,
    UQSHLR,
    UQSHRN,
    UQSHRNB,
    UQSHRNT,
    UQSUB,
    UQSUBR,
    UQXTN,
    UQXTNB,
    UQXTNT,
    URECPE,
    URHADD,
    URSHL,
    URSHLR,
    URSHR,
    URSQRTE,
    URSRA,
    USDOT,
    USHL,
    USHLL,
    USHLLB,
    USHLLT,
    USHR,
    USMLALL,
    USMMLA,
    USMOP4A,
    USMOP4S,
    USMOPA,
    USMOPS,
    USQADD,
    USRA,
    USTMOPA,
    USUBL,
    USUBLB,
    USUBLT,
    USUBW,
    USUBWB,
    USUBWT,
    USVDOT,
    UTMOPA,
    UUNPK,
    UUNPKHI,
    UUNPKLO,
    UVDOT,
    UXTB,
    UXTH,
    UXTW,
    UZP,
    UZP1,
    UZP2,
    UZPQ1,
    UZPQ2,
    WFE,
    WFET,
    WFI,
    WFIT,
    WHILEGE,
    WHILEGT,
    WHILEHI,
    WHILEHS,
    WHILELE,
    WHILELO,
    WHILELS,
    WHILELT,
    WHILERW,
    WHILEWR,
    WRFFR,
    XAFLAG,
    XAR,
    XPACD,
    XPACI,
    XPACLRI,
    XTN,
    YIELD,
    ZERO,
    ZIP,
    ZIP1,
    ZIP2,
    ZIPQ1,
    ZIPQ2,
    UNKNOWN
};

// ARM64 condition codes
enum class Condition : int8_t {
    None = -1,
    EQ = 0,   // Equal
    NE = 1,   // Not equal
    CS = 2,   // Carry set / unsigned higher or same (HS)
    CC = 3,   // Carry clear / unsigned lower (LO)
    MI = 4,   // Minus / negative
    PL = 5,   // Plus / positive or zero
    VS = 6,   // Overflow
    VC = 7,   // No overflow
    HI = 8,   // Unsigned higher
    LS = 9,   // Unsigned lower or same
    GE = 10,  // Signed greater than or equal
    LT = 11,  // Signed less than
    GT = 12,  // Signed greater than
    LE = 13,  // Signed less than or equal
    AL = 14,  // Always
    NV = 15   // Never (behaves like AL)
};

// Operand type enumeration
enum class OperandType {
    Register,           // General purpose register (Xn, Wn)
    VectorRegister,     // Vector/SIMD register (Vn, Qn, Dn, Sn, Hn, Bn)
    SVERegister,        // SVE scalable vector register (Zn)
    PredicateRegister,  // SVE predicate register (Pn)
    SMETileRegister,    // SME tile register (ZAn)
    Immediate,          // Immediate value
    SignedImmediate,    // Signed immediate value
    MemoryBase,         // Memory operand [base]
    MemoryOffset,       // Memory operand [base, #offset]
    MemoryPreIndex,     // Memory operand [base, #offset]! (pre-index writeback)
    MemoryPostIndex,    // Memory operand [base], #offset (post-index writeback)
    MemoryRegOffset,    // Memory operand [base, Rm{, extend {#amount}}]
    Label,              // Branch target label/offset
    Relative,          // PC-relative offset for branches
    SystemRegister,     // System register
    Shift,              // Shift specifier (LSL, LSR, ASR, ROR)
    Extend,             // Extend specifier (UXTB, SXTW, etc.)
    Index,              // Element index
    Pattern,            // SVE pattern specifier
    Prefetch,           // Prefetch operation
    Barrier,            // Barrier option
    FloatImmediate,     // Floating-point immediate (#0.0, etc.)
    Unknown
};

// Operand representation
class Operand {
public:
    Operand() = default;

    // Constructor for simple operands (registers, immediates)
    Operand(OperandType t, uint32_t v, bool is_64 = true)
        : type(t), value(v), is_64bit(is_64) {}

    // Constructor for memory operands
    Operand(OperandType t, uint32_t base, int32_t off, uint32_t idx_reg = 0, uint32_t ext = 0, uint32_t amt = 0)
        : type(t), base_reg(base), offset(off), index_reg(idx_reg), extend(ext), amount(amt) {}

    // Static factory methods for memory operands
    static Operand memory_base(uint32_t base) {
        return Operand(OperandType::MemoryBase, base, 0);
    }
    static Operand memory_offset(uint32_t base, int32_t offset) {
        return Operand(OperandType::MemoryOffset, base, offset);
    }
    static Operand memory_pre_index(uint32_t base, int32_t offset) {
        return Operand(OperandType::MemoryPreIndex, base, offset);
    }
    static Operand memory_post_index(uint32_t base, int32_t offset) {
        return Operand(OperandType::MemoryPostIndex, base, offset);
    }
    static Operand memory_reg_offset(uint32_t base, uint32_t index, uint32_t extend = 0, uint32_t amount = 0) {
        return Operand(OperandType::MemoryRegOffset, base, 0, index, extend, amount);
    }

    OperandType type = OperandType::Unknown;
    uint32_t value = 0;          // Raw field value for simple operands
    uint64_t imm64 = 0;          // 64-bit immediate value (for logical immediates)
    bool is_64bit = true;        // True for 64-bit registers (X), false for 32-bit (W)
    bool is_sp = false;          // True if reg 31 should be SP/WSP, false for XZR/WZR
    const char* arrangement = nullptr;  // Vector arrangement specifier (.16b, .4s, etc.)
    uint32_t index = 0;           // Element index for indexed vector operands (v0.b[3])
    bool has_index = false;       // True if index field is valid

    // Memory operand fields
    uint32_t base_reg = 0;       // Base register number
    int32_t offset = 0;          // Signed offset
    uint32_t index_reg = 0;      // Index register for reg+reg addressing
    uint32_t extend = 0;         // Extend type for reg+reg addressing
    uint32_t amount = 0;         // Shift/extend amount

#ifndef VEDA64_NO_STRINGS
    // Format operand for disassembly
    std::string to_string() const;

private:
    // Helper functions for formatting
    static std::string format_register(uint32_t reg, bool is_64bit, bool is_sp = false);
    static std::string format_vector_register(uint32_t reg, const char* arrangement);
#endif
};

#ifndef VEDA64_NO_STRINGS
// Convert mnemonic enum to string
const char* mnemonic_to_string(Mnemonic mnem);

// Determine vector arrangement for MOVI/MVNI based on Q and cmode fields
const char* get_movi_arrangement(uint32_t insn);

// Convert condition code to string ("eq", "ne", etc.)
const char* condition_to_string(Condition cond);
#endif

// Instruction representation
class Instruction {
public:
    Instruction() = default;
    Instruction(Mnemonic mnem, uint32_t raw)
        : mnemonic(mnem), raw_value(raw) {}

    Mnemonic mnemonic = Mnemonic::UNKNOWN;
    Condition condition = Condition::None;
    uint32_t raw_value = 0;
    std::vector<Operand> operands;

#ifndef VEDA64_NO_STRINGS
    // Format as disassembled instruction
    std::string to_string() const;
#endif
};

// Decode a single ARM64 instruction from a uint32_t (native little-endian value)
std::optional<Instruction> decode(uint32_t insn);

// Decode a single ARM64 instruction from 4 bytes in memory (little-endian)
inline std::optional<Instruction> decode(const uint8_t* bytes) {
    return decode(from_bytes(bytes));
}

// ============================================================================
// Hook API (Windows ARM64 inline hooking)
// ============================================================================

#if !defined(VEDA64_NO_HOOKS) && (defined(_WIN32) || defined(VEDA64_HOOK_SUPPORT))

namespace hook {

// Forward declarations
struct HookContext;
struct Trampoline;

// Hook status codes
enum class HookStatus {
    Success = 0,
    NotInitialized,
    InvalidTarget,
    InvalidDetour,
    AllocationFailed,
    ProtectionFailed,
    DisassemblyFailed,
    RelocationFailed,
    InstructionTooComplex,
    HookAlreadyInstalled,
    HookNotFound,
    HookDisabled,
    InternalError
};

#ifndef VEDA64_NO_STRINGS
// Convert status to string
const char* status_to_string(HookStatus status);
#endif

// Hook handle - opaque pointer to hook context
using HookHandle = HookContext*;

// Hook configuration options
struct HookConfig {
    // Minimum bytes to overwrite (default: 16 for LDR+BR sequence)
    size_t min_hook_size = 16;

    // Maximum instructions to relocate in trampoline
    size_t max_relocated_insns = 32;

    // Enable thread-safe hook installation (uses suspend/resume)
    bool thread_safe = true;

    // Preserve CPU flags across hook
    bool preserve_flags = true;

    // Allow hooking of already-hooked functions (chain hooks)
    bool allow_chain = false;
};

// Global configuration
void set_config(const HookConfig& config);
HookConfig get_config();

// Initialize the hooking subsystem
// Must be called before any other hook functions
HookStatus initialize();

// Shutdown the hooking subsystem
// Automatically removes all installed hooks
void shutdown();

// Check if hooking subsystem is initialized
bool is_initialized();

// Install an inline hook (starts disabled — call enable() to activate)
// target: address of function to hook
// detour: address of your hook function
// original: receives pointer to trampoline for calling original function
// handle: optional output — receives handle to the hook
// Returns: HookStatus indicating success or failure
HookStatus install(void* target, void* detour, void** original, HookHandle* handle = nullptr);

// Remove a previously installed hook
// Restores original bytes and frees trampoline
HookStatus remove(HookHandle handle);

// Remove all hooks
void remove_all();

// Enable a disabled hook
HookStatus enable(HookHandle handle);

// Disable a hook (restores original bytes but keeps trampoline)
HookStatus disable(HookHandle handle);

// Enable all installed hooks
HookStatus enable_all();

// Disable all installed hooks
HookStatus disable_all();

// Check if hook is enabled
bool is_enabled(HookHandle handle);

// Get hook information
void* get_target(HookHandle handle);
void* get_detour(HookHandle handle);
void* get_trampoline(HookHandle handle);

// Get number of bytes overwritten at target
size_t get_hook_size(HookHandle handle);

// Get number of instructions relocated to trampoline
size_t get_relocated_count(HookHandle handle);

#ifndef VEDA64_NO_STRINGS
// Debug: Dump hook information
void dump_hook(HookHandle handle);
#endif

// ============================================================================
// Low-level API for advanced usage
// ============================================================================

namespace detail {

// Generate a jump sequence to target address
// buffer: output buffer (must be at least 16 bytes)
// target: destination address
// Returns: number of bytes written
size_t generate_jump(uint8_t* buffer, void* target);

// Generate a call sequence (saves return address)
// buffer: output buffer (must be at least 16 bytes)
// target: destination address
// Returns: number of bytes written
size_t generate_call(uint8_t* buffer, void* target);

// Check if an instruction is PC-relative
bool is_pc_relative(uint32_t insn);

// Check if an instruction can be safely relocated
bool can_relocate(uint32_t insn);

// Relocate a single instruction to a new address
bool relocate_instruction(
    uint32_t insn,
    uint64_t old_pc,
    uint64_t new_pc,
    uint32_t* out_insn,
    size_t* out_count
);

// Allocate executable memory for trampolines
void* alloc_executable(size_t size);

// Free executable memory
void free_executable(void* ptr, size_t size);

// Make memory region writable temporarily
// Returns previous protection value
uint32_t make_writable(void* addr, size_t size);

// Restore memory protection
void restore_protection(void* addr, size_t size, uint32_t old_protect);

// Flush instruction cache
void flush_icache(void* addr, size_t size);

// Suspend all threads except current (for safe hook installation)
void suspend_threads();

// Resume all suspended threads
void resume_threads();

} // namespace detail

} // namespace hook

#endif // !VEDA64_NO_HOOKS && (_WIN32 || VEDA64_HOOK_SUPPORT)

} // namespace veda64
