// veda64-disasm - ARM64 instruction disassembler
// Auto-generated by parse_arm64_xml.py
#include "veda64.hpp"
#include <iostream>
#include <cstdlib>

using namespace veda64;

// Parse a uint32_t from string (little-endian memory order)
bool parse_instruction(const char* str, uint32_t& value) {
    char* endptr;

    if (str[0] == '0' && (str[1] == 'x' || str[1] == 'X')) {
        value = static_cast<uint32_t>(std::strtoul(str + 2, &endptr, 16));
    } else if (str[0] == '0' && (str[1] == 'b' || str[1] == 'B')) {
        value = static_cast<uint32_t>(std::strtoul(str + 2, &endptr, 2));
    } else {
        value = static_cast<uint32_t>(std::strtoul(str, &endptr, 0));
    }

    return *endptr == '\0';
}

void print_usage(const char* progname) {
    std::cerr << "Usage: " << progname << " <instruction> [instruction...]\n";
    std::cerr << "\n";
    std::cerr << "Disassemble one or more ARM64 instructions.\n";
    std::cerr << "\n";
    std::cerr << "Arguments:\n";
    std::cerr << "  instruction  32-bit value in little-endian memory order\n";
    std::cerr << "               (hex: 0x..., binary: 0b..., or decimal)\n";
    std::cerr << "\n";
    std::cerr << "Examples:\n";
    std::cerr << "  " << progname << " 0x7f2303d5              # PACIBSP\n";
    std::cerr << "  " << progname << " 0xc0035fd6              # RET\n";
    std::cerr << "  " << progname << " 0x7f2303d5 0xc0035fd6   # Multiple instructions\n";
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }

    int errors = 0;

    for (int i = 1; i < argc; i++) {
        uint32_t insn;

        if (!parse_instruction(argv[i], insn)) {
            std::cerr << "Error: Invalid instruction value: " << argv[i] << "\n";
            errors++;
            continue;
        }

        auto result = decode(insn);

        if (result) {
            std::cout << "0x" << std::hex << insn << std::dec << ": " << result->to_string() << "\n";
        } else {
            std::cout << "0x" << std::hex << insn << std::dec << ": <unknown>\n";
        }
    }

    return errors > 0 ? 1 : 0;
}
